New package: code-server
spack/spack pull request #16076
Opened 2020-04-15 18:07 UTC by qwertos

2020-04-15 21:09 UTC, adamjstewart commented
Is it possible to install this package from source? The binaries distributed won't be optimized for any hardware, and won't support any other OS.

2020-04-16 13:04 UTC, qwertos commented
I looked into doing a source build, and the devs provide zero documentation for that. They seem to be in the mindset of "why would anyone want to build from source when we have this beautiful docker image and binary build". I'll take another look at it.

2020-04-17 01:47 UTC, hartzell commented
> "why would anyone want to build from source when we have this beautiful docker image and binary build"

We need to do a [Demotivational Poster](https://despair.com/collections/demotivators), "Docker, building from source is a thing of the past!".

So sad!

2020-10-11 02:26 UTC, adamjstewart commented
@qwertos is this still a work in progress?

2020-10-12 14:05 UTC, qwertos commented
Technically, yes. Functionally, it's so far down on my to do list that I don't know when I'm going to get back to it. I won't object to someone picking up the torch (or merging as is using the pre-built binaries).

2020-10-12 19:01 UTC, adamjstewart requested changes
Let's just merge as is with the binary package and someone can figure out the source build later. Can you make a few changes to the install method?

2020-10-12 19:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/code-server/package.py
> +        cp('-r', '{0}/.'.format(self.stage.source_path), prefix)
```suggestion
        install_tree('.', prefix)
```

2020-10-12 19:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/code-server/package.py
> +        ln('-s', '{0}/code-server'.format(prefix), prefix.bin)
```suggestion
        symlink('{0}/code-server'.format(prefix), prefix.bin)
```

2020-10-12 19:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/code-server/package.py
> +        cp = which('cp')
You can remove these. Spack has builtin tools for all of these that will work regardless of OS. We plan on adding Windows support in the near future.

2020-11-06 18:56 UTC, adamjstewart approved these changes

2020-11-06 18:56 UTC, merged