Command: Add option to add/remove environment includes
spack/spack pull request #44285
Opened 2024-05-21 03:32 UTC by kwryankrattiger

Add option to add includes for configs and concrete environments to an environment.

2024-05-21 20:09 UTC, kwryankrattiger commented on lib/spack/spack/test/cmd/env.py
> +
Test remove

2024-06-01 01:22 UTC, tldahlgren requested changes
It would be good for the new tests to check that the environment itself has the right set(s) of specs (e.g., `spec_lists` and included concrete specs) or other configuration information (if added) at each stage.  

It could also be helpful to also have a test or two that start(s) with an environment that has a concrete include and make sure the environment's spec lists are as they would be expected at each stage.

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/cmd/env.py
> +def env_include_setup_parser(subparser):
It will be good to update the documentation, especially in the `Updating an included environment` section (https://spack.readthedocs.io/en/latest/environments.html#updating-an-included-environment) and `Configuring Environments` section (https://spack.readthedocs.io/en/latest/environments.html#included-configurations) so it is clear how the changes for this PR relate to the existing include concrete feature.

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/cmd/env.py
> +    """Add/remove configuration scopes or concrete environments to the environment"""
The comment is a bit awkward from a `--help` perspective:

```
$ spack env -h
usage: spack env [-h] SUBCOMMAND ...

manage virtual environments

positional arguments:
  SUBCOMMAND
    activate   set the current environment
    deactivate
               deactivate any active environment in the shell
    create     create a new environment
    remove (rm)
               remove an existing environment
    rename (mv)
               rename an existing environment
    list (ls)  list managed environments
    status (st)
               print whether there is an active environment
    loads      list modules for an installed environment '(see spack module loads)'
    view       manage a view associated with the environment
    include    Add/remove configuration scopes or concrete environments to the environment
    update     update environments to the latest format
    revert     restore environments to their state before update
    depfile    generate a depfile from the concrete environment specs

optional arguments:
  -h, --help   show this help message and exit
```

Perhaps indicate the subcommand applies to the active environment.

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/cmd/env.py
> +def env_include_setup_parser(subparser):
Please remind me:  Why is there not an `include` and `remove` subcommand?

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/cmd/env.py
> +        "--prepend", action="store_true", help="Prepend the includes instead of append"
If `--prepend` stays as the `include` subcommand for both add and remove, then `--prepend` and `--remove` should not be allowed together.

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/test/cmd/env.py
> +            spack.util.spack_yaml.dump(package_config_f.format(spec=spec), stream=fd)
These files don't have the expected format, for example one of the `packages.yaml` files is:

```
"\npackages:\n  libelf:\n    externals:\n    - spec: abseil-cpp@20240116.2\n     \
\ prefix: /usr\n"
```

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/test/cmd/env.py
> +    test = ev.read("test")
It would be good to have a comment explaining what you're checking in this phase (e.g., confirm includes reflect the expected order).

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/test/cmd/env.py
> +    with test:
A comment explaining that the next phase is to remove an include and confirm that the includes are as expected would be good here.

2024-06-01 01:22 UTC, tldahlgren commented on lib/spack/spack/test/cmd/env.py
> +    """Test that adds includes to an environment"""
Removal is now part of this test so would be good for it to be reflected in the description, such as something along the lines of:  `Test adding and removing includes from an active environment result in the expected ordering of the includes.`

2024-06-01 01:24 UTC, tldahlgren commented on lib/spack/spack/test/cmd/env.py
> +            spack.util.spack_yaml.dump(package_config_f.format(spec=spec), stream=fd)
An `fd.write()` will output the proper format (though you may want to get rid of the starting `\n`).

2024-06-06 18:30 UTC, kwryankrattiger commented on lib/spack/spack/cmd/env.py
> +def env_include_setup_parser(subparser):
There is already a remove, which removes a managed environment. I thought about just having a new `include` and `remove` commands like `add`, but remove is already implemented to remove specs.

I could do something like

```
spack includes add [options...] <path or environment name>
spack includes remove [options...] <path or environment name>
```

2024-06-06 18:44 UTC, kwryankrattiger commented on lib/spack/spack/cmd/env.py
> +        "--prepend", action="store_true", help="Prepend the includes instead of append"
Right. I think breaking `--remove` into a sub command of a top level `includes` command may make more sense here.

2024-06-06 20:37 UTC, tldahlgren commented on lib/spack/spack/cmd/env.py
> +def env_include_setup_parser(subparser):
Now that I think about it overloading `remove` probably isn't a good idea.

So I like the commands you propose better.  Worth asking others on the core team though.

2024-07-12 17:10 UTC, tldahlgren commented
Adding @tgamblin at his off-line request.

2024-12-05 01:19 UTC, tldahlgren requested changes
It's looking good. I have some documentation suggestions and am not keen on the placement of `--concrete`.

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +   $ spack -e included_env include --concrete add /absolute/path/to/environment1
TBH. I'm not a fan of having the `--concrete` option appear before the subcommand.  There is a precedent for having such options added to each subcommand to which they apply (e.g., see https://spack.readthedocs.io/en/latest/command_index.html#spack-mirror).

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +It is possible to add or remove configurations to the current active environment
Not sure about final formatting, but:

```suggestion
You can add and remove configuration files in the current active environment
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +  $ spack env create myotherenv
Should this be `externalpython`?

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +environment name or by path.
Not sure about final formatting but:

```suggestion
Or you can use the command line to include concrete environments using their name or path.
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +
I'd like to see this as a separate subsection, such as `Listing environment includes`.

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +from the command line use the ``spack include --concrete list`` command.
Since the command also works for includes, perhaps something like the following (preferably under a separate subsection):

```suggestion
You can list includes for the active environment
at the command line using the
``spack include list`` command. For example,
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +from the command line use the ``spack include --concrete list`` command.
I see the following after adding a `definitions.yaml` file to one of my environments:

```
$ spack include list
==> Included Configuration Scopes
==> 
	definitions.yaml ($spack/var/spack/environments/defs/definitions.yaml)
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +  $ spack -e included_env concretize
This doesn't quite fit the subsection heading goal of explaining how to ensure the environment gets the latest versions of included environments.  Perhaps it should be a separate subsection about updating includes (e.g., `Updating environment includes`)?

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +added or removed. For example if ``myenv`` were to be removed and a new environment
Perhaps something along the lines:

```suggestion
Changes to environment includes require reconcretizing the environment.
For example if ``myenv`` were to be removed and a new environment
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/spack/cmd/include.py
> +    )
As I mentioned elsewhere, the precedent is to have each subcommand have its own arguments so this would need to be repeated for each.  See the `spack mirror` command for an example.

Having it appear before the subcommands feels awkward and, IMO, not user-friendly (as in harder to remember).

```
$ spack include list   # lists included configurations
$ spack include list --concrete  # lists included concrete
```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +
```suggestion
Be sure to use the path of the includes on the command line.

```

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/docs/environments.rst
> +
Above could be a hint.

The reason I bring it up is that `spack include list` will give a filename for a file (along with the absolute path). So I can see someone trying to use the filename and wondering why that doesn't work.

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/spack/cmd/include.py
> +        invalid = env.manifest.add_includes(args.includes, concrete=args.concrete)
It would be handy to support names of Spack-managed environments (e.g., converted to the  path using spack.environment.env_root_path()).

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/spack/cmd/include.py
> +    with env.write_transaction():
Would be nice to be able to support the name of a Spack-managed environment here as well.

2024-12-05 01:19 UTC, tldahlgren commented on lib/spack/spack/cmd/include.py
> +        setup_parser_cmd_name = "include_%s_setup_parser" % name
Use an f-string here.

2026-05-23 16:58 UTC, kwryankrattiger commented
This should be handled after merging https://github.com/spack/spack/pull/50207

Closing for now since it isn't urgent for the common stacks, which will use static and conditional includes.

2026-05-23 16:58 UTC, closed without merging