find_libraries: improve heuristics and cap max depth
spack/spack pull request #47481
Opened 2024-11-07 14:17 UTC by haampie

- **find_libraries: use targeted, iterative deepening with default max depth**
- **tests: improve file_list.py search order test**

2024-11-07 16:27 UTC, haampie commented on lib/spack/llnl/util/filesystem.py
> +    if os.path.basename(root) != "include":
Not sure if I should apply lowercase here

2024-11-07 16:28 UTC, haampie commented on lib/spack/llnl/util/filesystem.py
> +    if os.path.basename(root) not in common_lib_dirs:
also here I could just lowercase this

2024-11-07 16:31 UTC, haampie commented
This needs a "rebuild all" after an initial review

2024-11-07 16:36 UTC, haampie commented
@johnwparent what about header directories on windows?

2024-11-07 16:41 UTC, johnwparent commented
> @johnwparent what about header directories on windows? Currently on develop we seem to almost always assume they are in `<prefix>/include/`.

There are a few packages that really stick to the "flat install prefix" idiom and everything just gets slapped into `<prefix>`, so I don't know that we can get away with skipping the root `<prefix>` search. That said, the case where headers go into a flat install directory is rare enough that it would be reasonable to delegate that issue to the caller if that is more in line with the goals of your work here.

2024-11-07 16:48 UTC, haampie commented
OK, notice that already https://github.com/spack/spack/blob/bf11fb037b799d8643d096dfb0991c33b801a716/lib/spack/spack/spec.py#L1113 so I guess some things may be broken on windows even with develop then. The change after this PR is that explicit calls to `find_headers(path)` in `package.py` use a search heuristic by default, skipping `path/*.h` but looking at `path/include/*.h`

2024-11-07 16:51 UTC, johnwparent commented
> OK, notice that already
> 
> https://github.com/spack/spack/blob/bf11fb037b799d8643d096dfb0991c33b801a716/lib/spack/spack/spec.py#L1113
> so I guess some things may be broken on windows even with develop then. The change after this PR is that explicit calls to `find_headers(path)` in `package.py` use a search heuristic by default, skipping `path/*.h` but looking at `path/include/*.h`

Right, like I said, the flat install is an edge case, so it's not unreasonable for the default to be the standard behavior and allow callers to modulate as appropriate. So long as your enhancements here don't prevent that, then that default is fine.

2024-11-07 21:16 UTC, haampie commented
Blocked by #47488

2024-11-09 15:07 UTC, tgamblin commented
@spackbot rebuild everything

2024-11-11 09:57 UTC, haampie commented
3 failures:

- [ ] `py-onnx@1.16.2` `#include "absl/strings/string_view.h"`
- [ ] `sdl2@2.30.3` `#include <X11/extensions/Xdbe.h>`
- [ ] `unibilium@2.0.0` on darwin, unclear what the problem is

2024-11-11 12:00 UTC, haampie commented
The PR got a bit larger since `recursive=True` had to be eliminated from various places.

Also note that `find_headers`'s default went from `recursive=False` to `recursive="heuristic"`, hopefully not problematic.

2024-11-12 17:13 UTC, haampie commented
Moved to 0.24 because it's touching too many packages last-minute.

2025-09-17 14:28 UTC, haampie commented on lib/spack/spack/llnl/util/filesystem.py
> +        found_libs = find(fallback_recursive, libraries, max_depth=1)
Nope, it's an explicit iterative deepening step, so it returns at depth 1.

2025-09-24 23:17 UTC, scheibelp requested changes
I have a couple requests about documentation, and one about testing.

Behavior appears to be unchanged - in summary:

1. packages that don't define `.libs` explicitly get recursive/max_depth=unlimited behavior by default (as before)
2. packages that define `.libs` and set `recursive=` (true or false) will get the same behavior (as before)
3. packages that define `.libs` and use the default parameters for `find_libraries/headers` will get flat search by default (as before)

Nearly all packages in builtin fall into [1, 2]

My high-level question is: what is your intended follow-up to this?

- If just `find_...` changes to do strategy=heuristic by default, that would create a discrepancy between [1, 3]
- updating `_libs_default_handler` to set `max_depth=2` was sufficient for me (this means you don't get hangs if someone accidentally adds a link dependency on a cmake external in /usr)
- Overall I think it's ideal if `find_...` searches more things by default, and `_default_x_handler` searches fewer things by default (that means users who go through the trouble of defining `.libs`/`.headers` easily find what they're looking for)

2025-09-24 23:17 UTC, scheibelp commented on lib/spack/spack/llnl/util/filesystem.py
> +            if strategy is ``"flat"``.
A couple of requests for behavior/docstring:

* I think this docstring should mention `max_depth` defaults to `2` when `strategy=heuristic` and is unlimited for `recursive=True`/`strategy=recursive`.
* Personally I think it's confusing that `find_libraries(..., strategy=heuristic, max_depth=None)` explicitly set by the user would also result in `2`.
  * If that persists, it should be documented here
* You might want to check for (and prohibit) `max_depth<0`, because some functions use that to mean "unlimited"

2025-09-24 23:17 UTC, scheibelp commented on lib/spack/spack/test/llnl/util/filesystem.py
> +        fs.find_headers(["*"], root, recursive=recursive, max_depth=max_depth)
With the introduction of the `strategy` parameter, I think it's worth testing invalid pairings (e.g. `find_...(recursive=False, strategy=heuristic)`).

2025-09-24 23:17 UTC, scheibelp commented on lib/spack/spack/llnl/util/filesystem.py
> +        return LibraryList(find(fallback_recursive, libraries, max_depth=max_depth))
As implemented, if a user says `find_libraries([libblas*, liblapack*]...)` then `strategy=heuristic` would consider itself successful if it found either - is that a concern? If so, it could keep track for each input library whether something was found that satisfies it.

2025-09-24 23:17 UTC, scheibelp commented on lib/spack/spack/llnl/util/filesystem.py
> +            Defaults to ``"flat"``.
(minor) might want to say here this parameter should not be set if `recursive` is set.

2026-06-02 02:01 UTC, closed without merging