Shared spack
spack/spack pull request #47615
Opened 2024-11-15 08:29 UTC by scheibelp

Partial redo of https://github.com/spack/spack/pull/11871, currently exclusively focusing on the parts related to making the Spack prefix read-only.

This PR makes a new checkout of Spack perform all writes outside of the Spack prefix except for installs [see note 1].

The following are moved outside of the Spack prefix:

1. gpg keys (conditionally: if they are not found at the old path)
2. cached downloads (unconditionally)
3. where modules are generated (conditionally: if they are not found at the old path)
4. where environments are stored (conditionally: if they are not found at the old path)

A new `paths` variable is introduced: `$per_spack_user`. This is at `~/.spack/x`, where `x` is the hash of the Spack prefix; this is for isolating resources that are likely specific to separate clones of Spack. While [1, 2] are more general and have moved to the global user cache, [3, 4] are considered specific to the spack instance, and have moved to `$per_spack_user`.

Generally speaking, this means that an old instance of Spack that `git pull`s this will continue installing to `$spack/opt/spack`, caching downloads in `$spack/var/spack/cache/`, etc.

[note 1] The only reasonable default installation target besides the Spack prefix is under ~, which could be disruptive (e.g. if ~ is mounted somewhere different than Spack). 

### Controlling install location

Spack now has a notion of "install scheme", a directory...

- where it installs things *by default* (configuration can override)
- where to look for additional configuration

There are two understood schemes: `in-spack` and `out-of-spack`; `in-spack` is the old install behavior (`$spack/opt/spack`); `out-of-spack` installs to `$per_spack_user/installs`. The preferred install scheme is `in-spack`, unless `out-of-spack` has an associated config or anything has been installed to it, or if `$spack` is not writable by the user. The install scheme can be explicitly selected with `spack --install-scheme` (but that should not generally be required).

Generally, this means that users have an easy mechanism for controlling `install_tree:root` on a per-spack basis, and updating it to point outside of Spack.

Notes:

- `--install-scheme` is a pre-config concept: you can't add/select install schemes with config
- There isn't an implied association between out-of-spack/in-spack and end-user/admin: in fact admins would likely want to work with `--install-scheme=out-of-spack` (this would allow them to install spack as root, then manage their spack installation as a different user that has more permissions than end users but not enough to modify the spack prefix or other things owned by root)

### Other changes:

- The `misc_cache` has also moved to `$per_spack_user` (which should avoid the need for `SPACK_USER_CACHE_PATH=...`)
- The install-scheme config scope is the preferred scope for modification (e.g. the results of `spack external find` would be dumped there) - this is expected to reduce/eliminate the need for `SPACK_DISABLE_LOCAL_CONFIG`
- There's a 2nd new config scope intended for admins to provide config to end users. It is disabled by `SPACK_DISABLE_LOCAL_CONFIG` or `spack --disable-end-user-config` (the latter is more-specific, allowing config from ~ and `/etc/spack/`)
    - Primarily, this is so an admin can tell users about an upstream
- This has a rudimentary audit to detect writes into the Spack prefix (`sys.addaudithook`)
    - Right now it's always enabled (even for `--install-scheme=in-spack`)

### Use cases/considerations

- apt install of Spack
- pip install of Spack
    - sub-case, with `--user`
- Admin provides spack to users
    - but users might choose to clone spack themselves
    - and they may or may not want to use an admin-curated upstream
- `~` may or may not have significant storage space
- simple config management
    - admin should be able to define config that only applies to users, not admins
    - users may want their install location to differ on a per-spack basis (but still live outside of the spack prefix)
- Handling new/old spack instances: the logic should make sense for
    - new `git clone`s of spack
    - `git pull`s in existing clones (and e.g. should be able to use gpg keys)
    - Discarding a pre-existing download cache is not a problem

### Things not translated from #11871 

If prefixed w/ "drop", I think we can skip it entirely; "todo here" means "probably useful here"

- (todo here) Upstreams were refactored to work without configuration
    - This is considered a good idea, but isn't strictly required to make Spack `apt`/`pip`-installable
- (todo here) Permissions customization for install trees
- (drop) Roughly speaking, the concept of an install scheme was handled at the config level in 11871
    - This was somewhat awkward because we want to associate config with an install scheme: if we parse config to find the install tree, the install tree can then introduce more config that overrides the original config
    - It did however allow for quickly swapping between several install trees; I don't anticipate that is a common desire though.

2024-11-15 16:48 UTC, psakievich commented
@matthewcurry

2025-01-15 00:50 UTC, matthewcurry commented
I've driven this around extensively, poking in particular at upstream use cases. It would appear that upstreams has advanced enough since #11871 that a number of problems fixed in the original patch set are no longer an issue.

So far as upstreams working without configuration, I also noticed that an shared installation could configure _itself_ as an upstream in $spack/etc/spack/defaults/upstreams.yaml, and that just worked for both the upstream user and a different user loading that spack instance. Neat! Probably not the greatest way to do it, but allows for doing something close until we have time to do another PR.

2025-01-15 22:55 UTC, scheibelp commented
> I also noticed that a shared installation could configure itself as an upstream in $spack/etc/spack/defaults/upstreams.yaml, and that just worked for both the user managing that spack instance and a different user loading that spack instance. Neat! Probably not the greatest way to do it, but allows for doing something close until we have time to do another PR.

FWIW I added the `end-user` config scope so that this could be handled in a conceptually straightforward way:

* Admins put config in `/etc/spack/end-user` setting their spack install tree as an upstream
* When they run, they do `spack --disable-end-user-config install...` and in their case, the upstream isn't used

In other words, I didn't expect what you did to work. We might want to prevent that from happening, because I'm not sure what is actually going on when the upstream is the same as the root.

(this is mentioned in the subsection "New config scopes for user/admin interaction"; it would also be possible to implicitly omit an upstream if it matches the root)

2025-01-31 00:48 UTC, matthewcurry commented
I generally think this is very useful, and is specifically useful for pip/apt. What do we need to do to get this beyond a draft? What can I do to help?

2025-06-03 00:56 UTC, scheibelp commented on lib/spack/spack/test/data/config/config.yaml
> +  # transmitted to the subprocesses on windows)
Latest commit https://github.com/spack/spack/pull/47615/commits/4cda8a25950c5f015b46e9f5f156e3a7221df237 adds this and the fix for the error encountered by the previous commit. To complete the picture (hopefully), the reason this concurrency issue comes up in this PR is that I forgot to keep the test `config.yaml` in sync; however, the error that occurred when I forgot this is not something that should have happened and reflects a concurrency issue with installations on Windows in general (which is why I set `concurrency=1` in that commit.

2025-06-03 21:41 UTC, matthewcurry commented
It would be good to add to the documentation for scopes. Here's something I wrote for configuration.rst, but would go much better in this PR:

```

#. **site-admin**: Stored in ``$(prefix)/etc/site-admin``. Settings
   here affect only *this instance* of Spack. This scope is designed
   to allow a system administrator to make settings available to other
   privileged users, e.g. those that have read access to the
   site-admin configuration directory. Those who cannot read this
   directory will skip this scope.

```

and

```

#. **this-spack**: Stored in the user configuration directory:
   ``~/.spack/$(spack_instance_id)``. This configuration affects a
   particular instance of Spack denoted by the instance ID, much
   like the site scope. A user of a read-only Spack instance can use
   this scope to modify its behavior.

```

2025-06-03 22:53 UTC, psakievich requested changes, later dismissed
Lot's of great work here.  Specific comments are added for sections I have design concerns on. I would also like to see some unit-tests for:

- XDG mapping/fall back behaviors. Seems like a lot of permutations are possible here. Seeing the tests would help me to spot and/or understand corner cases.
- site admin stuff (I'm kind of just trusting this works as intended without a use case or docs in front of me)
- file permission issue handling for users interfacing with an admin install

IMO Those seem to be the main new features that are not tested in the current test-suite.

2025-06-03 22:53 UTC, psakievich commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
It is weird to me to have the 3rd precedent option.  It injected between two environment variable relocation options that I would expect to behave the same way. Is there a reason to not have the fall-back write to config so it becomes 1 going forward?

The purpose of `SPACK_DATA_HOME` to me is to give users a way to give a spack specific alternative to `XDG_DATA_HOME` so I would expect them to behave exactly the same. I feel that IF we keep 3 it should actually be precedent 2 or 4. But I'm not convinced we need it.

2025-06-03 22:53 UTC, psakievich commented on lib/spack/spack/paths.py
> +# Environments follow the same precedence rules as installs
Same as above. Also, environments already have a config to relocate them: `config:environments_root`. So we could probably embed the logic in a function for both.

2025-06-03 22:53 UTC, psakievich commented on etc/spack/defaults/config.yaml
>    test_stage: $user_cache_path/test
Was this one missed in the conversion?

2025-06-03 22:53 UTC, psakievich commented on lib/spack/spack/paths.py
> +    return os.path.expanduser(spack_xdg_defined)
```suggestion
def _define_xdg_or_backup(xdg_base, backup):
    # xdg_base = {DATA_HOME, CONFIG_HOME, STATE_HOME, etc}
    spack_override = f"SPACK_{xdg_base}"
    xdg_var = f"XDG_{xdg_base}"
    if spack_override in os.environ:
        spack_xdg_defined = os.path.join(os.environ[spack_override], "spack")
    elif xdg_var in os.environ:
        spack_xdg_defined = os.path.join(os.environ[xdg_var], "spack")
    else:
        spack_xdg_defined = os.path.join(backup, "spack")
    return os.path.expanduser(spack_xdg_defined)
```

Can we just support an override of all XDG variables? I think that simplifies the precedent logic to the users. `config > SPACK_* > XDG_*`

Then we can delete the `spack_data_home_varname` variable and special logic for respecting it.

2025-06-03 22:53 UTC, psakievich commented on lib/spack/spack/util/path.py
> +    - $user_cache_path      The user cache directory ($XDG_DATA_HOME, unless overridden)
```suggestion
    - $user_cache_path      The user cache directory ($[SPACK,XDG]_DATA_HOME, unless overridden)
```
Not sure if this is clear, but is this the case or is this an exception? I think it should be the case.

2025-06-03 22:53 UTC, psakievich commented on lib/spack/spack/util/path.py
> +    - $spack_xdg_state_home Long-lived but not-essential cache
I find this name redirection confusing as a developer and a user. Can we map these names closer to what they are?

Like `misc_cache = $spack_xdg_state_home/$spack_instance/cache` could we call it `$misc_cache_base` instead? or just `state_home` if we want to keep the implied xdg mapping? 

If we want to explicitly tie xdg mapping to spack internal variables then I would propose doing it uniformly, but I think that will be a more disruptive change.

2025-06-04 06:31 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
> It is weird to me to have the 3rd precedent option. It injected between two environment variable relocation options that I would expect to behave the same way.

I assume we agree on 1/2 (explicit config options should dominate all else, and SPACK_DATA_HOME is an explicit request from the user to spack to put data somewhere)

I liked [3] because it allows an old instance of spack to behave the way it did, even if a user sets XDG_DATA_HOME; note that [3] is only activated if installs are detected), so new spack instances would move right to [4].

If we want old spack installs to start using XDG_DATA_HOME, then [3] can move to [4] (I think it should still exist though, because otherwise an old spack install that pulls this PR would stop using its old install path even if SPACK_DATA_HOME/XDG_DATA_HOME were not defined.

What is your preference?

> Is there a reason to not have the fall-back write to config so it becomes 1 going forward?

I think we should not auto-populate `config:install_tree`, because then it's impossible to distinguish spack's default choice from an explicit user direction (also why I removed the default setting).

2025-06-04 06:36 UTC, scheibelp commented on lib/spack/spack/paths.py
> +    return os.path.expanduser(spack_xdg_defined)
I wanted to keep track of e.g. XDG_DATA_HOME and SPACK_DATA_HOME separately for https://github.com/spack/spack/pull/47615#discussion_r2125757909, but if they end up "adjacent" in that list, then this implementation is good.

2025-06-04 07:40 UTC, scheibelp commented on lib/spack/spack/util/path.py
> +    - $spack_xdg_state_home Long-lived but not-essential cache
Short version: these can be removed and the defaults would be established in code, and I would prefer that to changing this.

Longer version:

For variables like this presented to the user, `spack_xdg_x_home` means "`xdg_x_home`, but with an extra spack subdirectory": that is intended to be interesting to users because (a) xdg_x_home is interesting and because (b) I assume they would always want to place it inside of a `spack` subdirectory within it (otherwise several spack-based directories could all live directly under e.g. XDG_CACHE_HOME, a location all programs share). The explanations here are intended to by why a user would care about expanding an `xdg_...` variable as part of a spack config value.

I think that answers your first and third sentence. For:

> Like misc_cache = $spack_xdg_state_home/$spack_instance/cache could we call it $misc_cache_base instead? or just state_home if we want to keep the implied xdg mapping?

IMO it would be preferable to not have a definition and to remove the default settings: I think expanding spack variables should exist when there is potential for them to be reused. If we make a variable called `misc_cache_base`, then that means "where we put the miscellaneous caches" and I don't think a user will have a desire to use that variable other than in 

`misc_cache: $misc_cache_base`

I think it would be clearer to just remove the default setting. I think users might possibly want to reuse XDG_X_HOME though, for example if they are familiar with the XDG spec and the implication of storing data in certain XDG variables, they could move the build stage from XDG_CACHE_HOME to XDG_DATA_HOME.

2025-06-04 08:41 UTC, scheibelp commented on etc/spack/defaults/config.yaml
>    test_stage: $user_cache_path/test
Short: I deliberately left it this way, but it doesn't have to be this way: some things in spack had to move as part of this PR, but this didn't.

Long:

Data in `user_cache_path`

1. is written dynamically by spack
2. must persist
3. doesn't amount to much data

Because of [3] (i think test run data generated by spack fits this) we can store it in the default value of XDG_DATA_HOME, i.e. inside of `~`; we'd like to do this for many things that fit [1] and/or [2], but things that take up space shouldn't live under `~` by default.

Things that don't meet criteria [3] must avoid `~` as a default which means they might fail if the spack prefix isn't writable, putting test data in `~` means that `spack unit-test` is an operation that is not limited in this way. 

SPACK_DATA_HOME is meant to be the bucket for things that don't fit criteria [3]. `user_cache_path` could move there if it were defined, but originally I felt that doing so would obfuscate the purpose of SPACK_DATA_HOME. I could see the appeal though of redirecting more things there if it were defined.

2025-06-04 13:59 UTC, psakievich commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
I agree that configs should dominate all else. I don't see `SPACK_DATA_HOME` as an explicit request to put data somewhere else though. I see it as a default in absence of a config. My idea for `SPACK_DATA_HOME` was that it distinguishes from `XDG_DATA_HOME` if users want special exceptions for spack from other `XDG_` compliant programs.   

Is the logic you're going for here of `SPACK_DATA_HOME` is akin to `SPACK_USER_CONFIG_PATH` in that it overrides on the instance?  I can see an argument to be made for that, but it isn't my preference. Also to do that I would rather that override config (highest precedent) as `SPACK_USER_CONFIG_PATH` does for consistency.

I think moving to `XDG_` largely eliminates the need for that behavior because it is a subset of what we get from xdg compliance. Now if users don't like the default user config location, they can change it.  Configs are a special case though since they dominate all else, so I suspect we still need/want `SPACK_USER_CONFIG_PATH` .

But for relocation of installs, I think we should really only tell users one way: configs. You want environment specific installs? `spack config add config:install_tree:root:$env/install` 

You want to do it per spack instance? Then drive it through the instance config for `install_tree`.

I think adding the level of dynamic behavior that is intended in with `SPACK_DATA_HOME` as implemented here adds additional complexity that is not necessary for the goal of the feature.

2025-06-04 14:15 UTC, psakievich commented on etc/spack/defaults/base/config.yaml
>    test_stage: $user_cache_path/test
Yeah I don't know if it needs to go to `SPACK_DATA_HOME` either. As long as it is getting piped to an `XDG_` path for the default variable that is all that matters. My initial impression was that criteria [3] wasn't going to need that many exceptions **because** of this feature. 

If I find that `~/.config/cache/spack` is getting too large, I can set `XDG_CACHE_HOME` or `SPACK_CACHE_HOME` to move it.  What **could** be too large for `HOME` is really a combination of the user behavior and the system restrictions.  I think this might be the crux of the conflict for the design decisions you and I are iterating on. 

Your intention seems to be capture as much intuition for the restricted `HOME` case as possible into the defaults. My preference is to just expose the ability to change those as needed and minimize the complexity of the implementation.

2025-06-04 17:29 UTC, matthewcurry commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
My opinion: I agree with Phil’s stance on SPACK_DATA_HOME should be adjacent to XDG_DATA_HOME in precedence, and they should both be higher precedence than existing install locations. I believed that the names were chosen to be similar because they were semantically supposed to do the same thing, so as a user I would expect them to be interchangeable in any situation if only one is defined.

2025-06-04 18:43 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
I can reorganize the precedence, and I think that will reduce some confusion.

Also I think I can make SPACK_DATA_HOME behave more like a stand-in for XDG_DATA_HOME which I think will also help.
 
I was thinking though based on this conversation, there is an opportunity to have SPACK_DATA_HOME pull in more state than XDG_DATA_HOME, mainly in the sense that I didn't think a user would want to define analogs of multiple XDG_ variables when SPACK_DATA_HOME doesn't have to be strictly burdened with the implied use of XDG_ variables - see https://wiki.debian.org/XDGBaseDirectorySpecification.

2025-06-04 20:55 UTC, psakievich commented on lib/spack/spack/paths.py
> +        return os.path.join(spack_data_home(), "installs")
Hmm I think I misread this first pass. So @scheibelp are you proposing that `SPACK_DATA_HOME` will behave differently than `XDG_DATA_HOME` or that we would just lump more things under the `*_DATA_HOME` suffixed directory.  If it is the former then I am opposed to that. I strongly feel that `SPACK_DATA_HOME` needs to just be a  spack specific version of `XDG_DATA_HOME` and that `SPACK_` and `XDG_` prefixes for directories should behave exactly the same way.

2025-06-05 08:30 UTC, scheibelp commented
Changes (not yet updated in PR description):

- paths.py variables called spack_xdg_x_home have been renamed to just xdg_x_home (I originally called them that to highlight that they had an additional subdirectory, but I think with the introduction of SPACK_DATA_HOME, that became confusing)
- Everything defined in an object (so tests can check what happens when certain environment variables are set)
    - and this object reorganizes all variables into sections with explanations
- Implemented precedence order for install trees discussed in https://github.com/spack/spack/pull/47615#discussion_r2125014791  (i.e. shifted a couple things around in order)
- SPACK_DATA_HOME now serves as the stand in for XDG_DATA_HOME in all cases (vs. before, most small-data items were not redirected to SPACK_DATA_HOME)

2025-06-05 17:56 UTC, psakievich reviewed
I like the direction of these changes. I still hold the opinion that `SPACK_DATA_HOME` shouldn't be special and that `SPACK_*` and `XDG_*` should mirror each other for all variables, we should commit more to that, and less to trying to be overly intuitive for the design. I am open to the idea that I am missing required  complexity the intuition needs to capture for backwards compatibility though. Looking forward to our discussion

2025-06-05 17:56 UTC, psakievich commented on lib/spack/spack/paths.py
> +        # setting `SPACK_USER_CACHE_PATH`. Otherwise it defaults to ~/.spack.
I don't have a real issue with this default. I think it mirrors a lot of other xdg projects. But to be pedantic, a more xdg/.config location seems like it would be `~/.cache/spack`. Then this becomes another `xdg_cache` variable which I would prefer. Just make things prefix to `xdg_cache_path/spack`, `xdg_data_home/spack` etc, and not make as many exceptions for behavior.

So `SPACK_USER_CACHE_PATH > SPACK_CACHE_PATH > XDG_CACHE_PATH > ~/.cache/spack`

2025-06-05 17:56 UTC, psakievich commented on lib/spack/spack/paths.py
> +class SpackPaths:
FWIW, I really like this. I've always felt like we need a clean API for paths for things like env var expansion etc.

2025-06-05 18:03 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        # setting `SPACK_USER_CACHE_PATH`. Otherwise it defaults to ~/.spack.
the `~/.spack` part of the comment was out of date. Any comment that implies writing into ~ but outside of XDG_ defaults is a mistake on my part (and any case where I actually do that is a large mistake on my part).

2025-06-05 20:10 UTC, psakievich reviewed
Reviewed post meeting. Mostly hints/suggestions. No real remaining design issues spotted from my end.

2025-06-05 20:10 UTC, psakievich commented on etc/spack/defaults/config.yaml
>    # - $spack/var/spack/stage
Probably want to update this commented default directory. Nothing should be defaulting to `$spack` now correct?

2025-06-05 20:10 UTC, psakievich commented on etc/spack/defaults/base/config.yaml
> -    root: $spack/opt/spack
Reminder, we agreed this should be like `$default_install_location` or something like that so it still shows up with `spack config blame config` in the default case.

2025-06-05 20:10 UTC, psakievich commented on etc/spack/defaults/modules.yaml
> -     lmod:   $spack/share/spack/lmod
Should we leave these as comments referencing the default locations like we do for some of the other configs? These end up in the docs so I'm thinking we should preserve them so users have an easy reference for the option. That's usually where I go for knowning the syntax of a particular config I want to start setting.

2025-06-05 20:10 UTC, psakievich commented on lib/spack/spack/test/cmd/commands.py
> +    # TODO: changes in this PR add a site-admin config scope. If one runs
```suggestion
    # TODO: changes in #47615 add a site-admin config scope. If one runs
```
Not sure this needs to get resolved in this PR. Just documenting history.

2025-06-05 20:10 UTC, psakievich commented on lib/spack/spack/test/config.py
> -def test_system_config_path_is_overridable(working_env):
Looks like these were deleted since they are tested in `test/paths.py`. I wonder if we want to keep them for an integration test for path resolution via config? Suggestion, not requirement if that seems like excessive test bloat.

2025-06-05 20:27 UTC, scheibelp commented on etc/spack/defaults/config.yaml
>    # - $spack/var/spack/stage
No write paths should default to `$spack` (and this comment should in fact be removed, and I have now done so)

It's correct to use it for `template_dirs` and `license_dir` (so there are still references to `$spack` in the default config)

2025-06-05 20:28 UTC, scheibelp commented on etc/spack/defaults/modules.yaml
> -     lmod:   $spack/share/spack/lmod
I restored this in the same spirit as https://github.com/spack/spack/pull/47615#discussion_r2130082985

2025-06-05 20:32 UTC, scheibelp commented on etc/spack/defaults/base/config.yaml
> -    root: $spack/opt/spack
Done now

2025-06-05 20:33 UTC, scheibelp commented on lib/spack/spack/test/config.py
> -def test_system_config_path_is_overridable(working_env):
These tests are basically moved: they were interacting with private methods in `paths`, so they had to be rewritten, but the tests in the `paths` test module are meant to be direct analogs of these.

2025-06-05 22:56 UTC, matthewcurry commented
# TL;DR: Data locations

Existing instances of Spack that upgrade in-place will continue to use the same data locations that have been used previously. However, new installs of Spack will see data placed in different locations, with XDG environment variables influencing their placement.

Spack uses three of the XDG variables:
 - XDG_DATA_HOME (default: `$HOME/.local/share`). A place for long-lived data Spack requires to work.
 - XDG_CONFIG_HOME (default: `$HOME/.config`). A place for configuration information.
 - XDG_STATE_HOME (default: `$HOME/.local/state`). A place for state that is useful if persistent, but not necessary for Spack to work.

Spack also includes a new configuration variable, `spack_instance_id`, that provides a short hash associated with an instance of Spack. This can be used to define instance-specific storage for install roots, configurations, and other types of data.

## What will be placed where?

### Default In-Spack
The following categories of data will be stored within the Spack instance if XDG variables are not defined.

Where are packages cached? (i.e., source_cache)
 -  Previous: `$spack/var/spack/cache`
 - No XDG variables: `$spack/opt/data`
 - With XDG: `$XDG_DATA_HOME/spack/downloads`

Where are packages installed (i.e., install_tree:root)?
 - Previous: `$spack/opt/spack`
 - No XDG variables: `$spack/opt/data`
 - With XDG: `$XDG_DATA_HOME/spack/installs`

### Default XDG locations
The following categories of data will be stored using default values of XDG variables if they are not defined.

Where are modules installed?
- Previous: `$spack/share/spack/`
- Otherwise: `$XDG_DATA_HOME/spack/modules`

Where are other caches (e.g., package indices) placed?
 - Previous: `~/.cache/spack`
 - Otherwise: `$XDG_STATE_HOME/$spack_instance_id/spack`

What is the highest-precedence configuration path?
 - Previous: `~/.spack`
 - Otherwise: `$XDG_CONFIG_HOME/spack/$spack_instance_id`

## Overriding XDG for Spack
If a user requires that Spack store in places that are different than what XDG variables define, there are a set of Spack-specific variables (called SPACK_DATA_HOME, SPACK_CONFIG_HOME, and SPACK_STATE_HOME) that will override their XDG counterparts. These behave exactly the same as the corresponding XDG variables.

2025-06-06 00:09 UTC, matthewcurry commented
# Configuration scopes

This PR introduces two configuration scopes that are intended to streamline the ability for system administrators to provide Spack instances and trees to system users. These two populations have different needs that need to be addressed with independent configurations.

## site-admin scope

For system administrators, there is the site-admin scope. It is located within the Spack instance at `$spack/etc/spack/site-admin`. Access to this scope is designed to be governed by read permissions -- if Spack cannot access the configurations in this directory, it cannot use it. This scope overrides only the default (`$spack/etc/spack`) and system (`/etc/spack`) scopes. One common way to use it would be to have end-user settings in `/etc/spack` while allowing administrator-specific overrides in the site-admin scope.

## per-spack scope

The per-spack configuration scope allows for a user to apply configurations directly to a Spack instance based on its hash, and is by default located in `~/.config/spack/$spack_instance_id`. This scope is useful when a user needs to configure a particular instance when the instance is not writable, such as when the instance is provided by a system-wide installation. This is the highest-precedence configuration location that is automatically evaluated, and is evaluated after `~/.spack`. Custom scopes are the only way to override it.

2025-06-06 01:22 UTC, scheibelp commented
The docs error I can reproduce on develop. On develop, it goes away if I 

``SPACK_USER_CONFIG_PATH=`pwd`/.spack spack info zlib``

inside of `lib/spack/docs/` . Not sure how to update the docs build to do that (and it probably isn't the right fix for it anyhow).

2025-06-06 04:56 UTC, becker33 requested changes

2025-06-06 04:56 UTC, becker33 commented on lib/spack/spack/test/data/config/config.yaml
> +  # transmitted to the subprocesses on windows)
This coment should either be removed or made general enough to be legible to someone who was not deeply involved in the writing process for this PR.

2025-06-06 04:56 UTC, becker33 commented on lib/spack/spack/installer.py
> +if sys.platform == "win32":
Can you explain to me why this issue only showed up now and never in testing the installer parallelism PR?

2025-06-06 04:56 UTC, becker33 commented on etc/spack/defaults/modules.yaml
> +     tcl:    $modules_base/modules
This should have a comment explaining what `$modules_base` is likely to mean for the user

2025-06-06 04:56 UTC, becker33 commented on etc/spack/defaults/config.yaml
> +    root: $default_install_root
All of the config defaults in this file that use "complex" values should have comments explaining to the user what these magic variables are likely to mean for them

2025-06-06 04:56 UTC, becker33 commented on lib/spack/spack/paths.py
> +        self.sbang_script = os.path.join(self.bin_path, "sbang")
I believe this location has been deprecated for several years now, we should consider removing it for 1.0

2025-06-06 04:56 UTC, becker33 commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
I understand from the tests that this value respects `SPACK_STATE_HOME`, but I'm having a really hard time figuring out how from the code. What am I missing?

2025-06-06 05:05 UTC, tgamblin commented on lib/spack/spack/paths.py
> +        self.sbang_script = os.path.join(self.bin_path, "sbang")
This is actually where we currently *vendor* `sbang`, and the `<install_tree>/bin/sbang` that is actually used in shebangs is copied from this location. I actually think this is an ok place to put `sbang`... it lets you call `sbang` to test it out if Spack is in your `PATH`.  Probably ok to remove it eventually but I don't think it's needed for `1.0`.  Also this path is used by the sbang hook to do the installation.

2025-06-06 05:17 UTC, psakievich commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
That is correct. @scheibelp I think you mentioned here: https://github.com/spack/spack/pull/47615#discussion_r2125051559 the reason for NOT doing this was the original gap in precedent between `SPACK_DATA_HOME` and `XDG_DATA_HOME`. Now that it is resolved it seems like we could just implement that?

2025-06-06 05:23 UTC, psakievich commented
I unresolved a couple of comments I made in prior reviews to make the context of prior discussions more apparent.

2025-06-06 05:24 UTC, scheibelp commented on lib/spack/spack/installer.py
> +if sys.platform == "win32":
https://github.com/spack/spack/pull/47615#discussion_r2131452507 is part of it: the configs matched so the subprocesses never tried to simultaneously generate an index. As for why it wouldn't have shown up otherwise, it's a race condition, so e.g. any pipelines would be unlikely to trigger it (the unit test is extremely good at triggering the race condition because it kicks off subprocesses which don't do much other than fight).

2025-06-06 05:25 UTC, scheibelp commented on lib/spack/spack/test/data/config/config.yaml
> +  # transmitted to the subprocesses on windows)
Agree, but I thought it would be useful for reviewers, e.g. https://github.com/spack/spack/pull/47615#discussion_r2131528659

2025-06-06 05:30 UTC, psakievich commented on lib/spack/spack/paths.py
> +        else:
```suggestion
            return os.environ[Location_vars.spack_data_home.value]
         elif self.xdg_state_home in os.environ:
            return os.path.expanduser(
                 os.path.join(os.environ[self.xdg_state_home], "spack", subdir)
             )
        else:
```

This might be useful if we expand the `SPACK_*` and `XDG_*` mapping. I think you can still do the small/large data mapping, but it would make it more consistent for the case where users are really into relying on `XDG_`.

The large/small data stands out to me as a case where the `SPACK_*` and `XDG_*` mapping bifurcation gets confusing. Adding this extra layer at least makes them more consistent.

2025-06-06 05:35 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
To be clear, you want it so that if a user sets `SPACK_STATE_HOME` and asks for `$xdg_state_home` in the configs, that it expands to `$spack_state_home`? I thought that would be unintuitive. 

Or are you thinking something like a canonicalization config var that clearly might expand to either like `$spack_or_xdg_state_home`?

Ignoring those lower level semantics and zooming out to the general behavior of SPACK_STATE_HOME providing an alternative: Compared to _DATA_HOME, I thought users would have less interest in setting `SPACK_STATE_HOME` as an override for XDG_STATE_HOME (because unlike things that go in _DATA_HOME, everything in STATE_HOME is small).

2025-06-06 05:36 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        self.sbang_script = os.path.join(self.bin_path, "sbang")
Sounds like this is a later thing: I'm going to mark this as resolved.

2025-06-06 05:41 UTC, psakievich commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
There is another use case for setting these variables that I use a lot. Content isolation. Currently I define and move everything small data I can to specific global directories per spack instance so it is easy to delete them and ensure there isn't cross pollination between spack instances. See discussion [here]( https://spackpm.slack.com/archives/C5W7NKZJT/p1749138991517309).

This the part of the spack specific instance with the hashes that I'm not clear on still. I don't know if that resolves my need there or not. But personally speaking, I DO value uniformity. So anything that would be `XDG_*` I would like to be `SPACK_*`.

2025-06-06 05:45 UTC, psakievich commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
To be clear though, my official stance for review would be, if making that change would be enough effort to keep this out of 1.0, I would rather stick with this to get it into 1.0. This is my strong preference. I won't withhold my final approval of the PR on it.

2025-06-06 05:47 UTC, scheibelp commented on etc/spack/defaults/config.yaml
> +    root: $default_install_root
I took a crack at it for this one - is that what you're looking for?

2025-06-06 05:51 UTC, scheibelp commented on lib/spack/spack/installer.py
> +if sys.platform == "win32":
See also: https://github.com/spack/spack/pull/47615#discussion_r2122399824

2025-06-06 06:00 UTC, becker33 commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
I think the config variable should probably be `spack_state_home`, and it should check `SPACK_STATE_HOME`, then `XDG_STATE_HOME`, then the default.

2025-06-06 06:12 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
> There is another use case for setting these variables that I use a lot. Content isolation. Currently I define and move everything small data I can to specific global directories per spack instance so it is easy to delete them and ensure there isn't cross pollination between spack instances. See discussion [here](https://spackpm.slack.com/archives/C5W7NKZJT/p1749138991517309).

Apologies but that doesn't seem to direct me to a conversation that seems relevant to this, but I think I understand your desire, that makes sense that you could set SPACK_STATE_HOME for each instance, although FWIW I tried to support that in this PR in another way: e.g. with

```
        self.default_misc_cache_path = os.path.join(
            self.xdg_state_home, self.spack_instance_id, "misc-cache"
        )
```

for each type data that I didn't want spack to share I put it in a subdir based on the instance ID, so that two spack instances could point at the same location and not interfere with each others' misc cache (for example)

2025-06-06 06:12 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
> I think the config variable should probably be spack_state_home, and it should check SPACK_STATE_HOME, then XDG_STATE_HOME, then the default.

That sounds good to me

2025-06-06 06:13 UTC, becker33 commented on etc/spack/defaults/config.yaml
> +    root: $default_install_root
I think one of the important things here is that someone reading the config can use it to figure out where the files were written. Maybe something like:
```suggestion
    # If set to a non-default value, that setting has precedence.
    # This default value tells spack to check (in order of precedence):
    # $SPACK_DATA_HOME/spack
    # $XDG_DATA_HOME/spack
    # $spack/opt/spack if previously used by an older version of spack
    # $spack/opt/data
    root: $default_install_root
```

2025-06-06 07:29 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        self.xdg_state_home = _define_xdg_or_backup(
I think this is addressed now

2025-06-06 07:29 UTC, scheibelp commented on etc/spack/defaults/config.yaml
> +    root: $default_install_root
I think this is addressed now

2025-06-06 07:30 UTC, scheibelp commented on etc/spack/defaults/modules.yaml
> +     tcl:    $modules_base/modules
I think this is addressed now

2025-06-06 07:33 UTC, runiq commented
> ## site-admin scope
> 
> For system administrators, there is the site-admin scope. It is located within the Spack instance at `$spack/etc/spack/site-admin`. Access to this scope is designed to be governed by read permissions -- if Spack cannot access the configurations in this directory, it cannot use it. This scope overrides only the defaults (`$spack/etc/spack/defaults`) and system (`/etc/spack`) scopes. One common way to use it would be to have end-user settings in `/etc/spack` while allowing administrator-specific overrides in the site-admin scope.

How would I override `$spack/etc/spack/site-admin` with per-system settings? Shouldn't `/etc/spack` have higher precedence than `$spack/etc/spack/site-admin`? Both are under the purview of admin staff anyways.

2025-06-06 07:39 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        else:
There are now `spack_` overrides for all XDG_ vars used in spack, so I think this bifurcation may be lessened. The large data home function is to highlight the need to distinguish between the case where the variable is explicitly defined (generally only important for _DATA_HOME).

This example appears to mix XDG_STATE_HOME and SPACK_DATA_HOME: was that intended?

2025-06-06 07:56 UTC, becker33 submitted a review, later dismissed
The changes mostly look great, some more comments that shouldn't lead to too much iteration

2025-06-06 07:56 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +    # $XDG_DATA_HOME/spack/installs
I'm a little concerned that `export SPACK_DATA_HOME=$XDG_DATA_HOME` will change behavior -- I don't think that's what we want. I think it's better to have the slightly redundant `SPACK_DATA_HOME/spack`.

@psakievich I'm curious what you think here as well.

2025-06-06 07:56 UTC, becker33 commented on lib/spack/spack/paths.py
> +    return saved
This method probably needs to unset the spack overrides too

2025-06-06 12:20 UTC, psakievich commented on etc/spack/defaults/config.yaml
> +    # $XDG_DATA_HOME/spack/installs
I agree. Good catch.

2025-06-06 12:29 UTC, psakievich commented on lib/spack/spack/paths.py
> +        val = os.environ[xdg_mapping.spack]
```suggestion
        val = os.path.join(os.environ[xdg_mapping.spack], "spack")
```
Per @becker33's comment, this would be more uniform between xdg and Spack variables. Hmmm now that I see it in code I'm not so sure. I suppose it would make scripting consistent if you switch them, but it does feel redundant from a user perspective too...

2025-06-06 12:29 UTC, psakievich commented on etc/spack/defaults/base/config.yaml
> +    # $XDG_DATA_HOME/spack/installs
Well I'm second guessing now. See comment below. Just woke up. I'll think some more. Both make sense to me ATM. Thinking about use cases.

2025-06-06 12:33 UTC, psakievich commented
> How would I override $spack/etc/spack/site-admin with per-system settings? Shouldn't /etc/spack have higher precedence than $spack/etc/spack/site-admin? Both are under the purview of admin staff anyways

@runiq you could do it with user scopes still. This is an instance specific override for admins. So a general policy for all spacks could go in `/etc/Spack` but if admins wanted "this" Spack to have special rules that is what the admin scope is for.

2025-06-06 13:24 UTC, adamjstewart commented
Why `~/.local/share/spack` instead of `~/.local/spack`?

2025-06-06 17:03 UTC, scheibelp commented
> How would I override $spack/etc/spack/site-admin with per-system settings? 

I think https://spack.readthedocs.io/en/latest/configuration.html#platform-specific-configuration would work for that

> Shouldn't /etc/spack have higher precedence than $spack/etc/spack/site-admin? Both are under the purview of admin staff anyways.

That makes sense: if someone pip-installs spack, then admins should still be able to override the config that comes with it.

2025-06-06 17:12 UTC, scheibelp commented
> Why `~/.local/share/spack` instead of `~/.local/spack`?

`.local/share/spack` is the default for XDG_DATA_HOME. I don't think any XDG_ defaults target `~/.local/` but rather subdirs of it.

2025-06-06 17:20 UTC, psakievich commented on etc/spack/defaults/config.yaml
> +    # $XDG_DATA_HOME/spack/installs
So thought experiments here

As a user I want to move my stuff from XDG_ to SPACK_

I wouldn't cp the entire XDG_, just the XDG_*/spack/*. So in that sense not adding the extra subdir makes sense to me. 

If I am using the config variable `$spack_cache_path` for instance then it really needs to absorb it either way. `$spack_cache_path=$XDG_CACHE_PATH/spack or $SPACK_CACHE_PATH(/spack seems optional/null)`

If I was swapping variable and had them set via shell it might be ugly in the scripts for things like `rm ${SPACK_CACHE_PATH:-XDG_CONFIG_PATH}/spack`.

Those sort of shell script stand-ins are the only place where I could see this be annoying to users. I think it would be more annoying to have an extra/unnecessary directory in the path. 

XDG implies a catch all for many programs so the subdirectory is mandatory. The SPACK prefixed versions imply spack specific so it doesn't really seem necessary. 

I think I am persuading myself that the current implementation might be better. But I am still on the fence and could be persuaded either way.

2025-06-06 17:37 UTC, scheibelp commented on lib/spack/spack/paths.py
> +    return saved
I think this is addressed now

2025-06-06 21:50 UTC, becker33 commented on etc/spack/defaults/config.yaml
> +    # $XDG_DATA_HOME/spack/installs
As discussed offline, we determined that @psakievich 's concern here is more important, and my concern can be handled through careful documentation.

2025-06-06 22:23 UTC, scheibelp commented on lib/spack/spack/util/path.py
> +    - $spack_xdg_state_home Long-lived but not-essential cache
I think the PR has moved a bit since this comment: the default settings have been restored, but with special default config values that respect XDG_/SPACK_ data home, also there is now just `spack_data_home` and not `spack_xdg_data_home`

So I think this comment should be closed

2025-06-06 22:25 UTC, scheibelp commented on lib/spack/spack/test/data/config/config.yaml
> +  # transmitted to the subprocesses on windows)
(now removed)

2025-06-07 07:06 UTC, tgamblin commented
I think this brought to light some races in the concretizer cache implementation. I reverted that and merged this back with `develop`. Hoping this puts it back on the right path -- sorry for the confusion... I should likely not have merged #49589. See #50851.

2025-06-09 00:19 UTC, psakievich submitted a review, later dismissed
Sigh, the `$misc_cache` is not what we wanted, but I think for now this is what we have to take. What is extra odd is #50595 is passing CI.

Updates beyond this comment rescind this statement.

2025-06-09 11:59 UTC, adamjstewart commented
> > Why `~/.local/share/spack` instead of `~/.local/spack`?
> 
> `.local/share/spack` is the default for XDG_DATA_HOME. I don't think any XDG_ defaults target `~/.local/` but rather subdirs of it.

Ah sorry, you're right. I was thinking of `~/.config/spack`, which is also a very commonly used directory.

2025-06-26 21:40 UTC, greenc-FNAL commented
@scheibelp Is this still aimed at 1.0?

2025-06-26 21:43 UTC, scheibelp commented
> Is this still aimed at 1.0?

No: it's now a 1.1 milestone

2025-06-27 14:37 UTC, greenc-FNAL commented
> No: it's now a 1.1 milestone

Argh, thanks.

2025-06-27 17:59 UTC, psakievich commented
I'm going to put some thoughts here, that I want to socialize for consideration. Might be too little too late, but here we go.

I think Spack got something very wrong with configs precedent, and I would submit this is why the user config has been so disruptive.

The current ordering of config scope precedent is:

1. Command line
2. environment
3. custom
4. user
5. plugin
6. site
7. system
8. default

However, I believe it *should have been*

1. Command line
2. environment
3. custom
4. **site**
5. plugin
6. **user**
7. system
8. default

The fact that the user aka `.config` scope overrides the instance settings is an area for a lot of heart burn when you are using multiple spack instances. This PR adds in a per instance scope which is hash-based and not in the install tree. I think this is the right move, but I think rather than adding a new scope we should just make that the new default `site` scope and reorder. 

I like the idea of a `user` scope to be my user defaults. What is lacking today is a clean way to override them for my spack instance. Currently, I get around that by using an environment for just about everything. That seems to just be a way to mitigate the symptom of a larger issue. I think that re-ordering the scopes is the cure. Adding more scopes adds more complexity. I submit that we can avoid that via reordering.

2025-08-06 12:28 UTC, alalazo commented
_(Adding this note as agreed during the last meeting)_

During the last meeting on this PR a few facts emerged, which can be summarized as follows:
1. The new scopes added in this PR are controversial, but are useful for certain use cases,
2. There is no list of scopes that is optimal for _all_ use cases, and
3. One requirement for this PR is to leave custom user configuration out of the Spack installation directory. 

### A central place to define scopes per Spack instance

One way to meet all the requirements above could be to _add a central place where users can optionally override the scopes considered by Spack_. 

This mechanism could work more or less in the following way:
1. Spack ships using the current scopes as a default. 
    * In this way users that are ok with the current state of things won't have to take any action after this PR is merged.
2. We can designate a central place where to define scopes per Spack instance
    * The default place could be, for instance, `$HOME/.config/spack/spack_instances.yaml` 
    * This will be a single file that drives how we construct the `Configuration` objects for potentially many instances of Spack.
    * It should be completely optional to have this file.
    * In case the default location of this file e.g. `$HOME/.config/spack` needs to be changed, we can do so by reading an environment variable e.g. `SPACK_INSTANCES_YAML_DIR`
3. Only the `system`, `site` and `user` scope can be subject to customization. This means that:
   * On the one hand the `_builtin` and `default:*` scopes will be always the lowest priority scopes, so that sane defaults are granted for any Spack instance
   * On the other hand, `custom`, `env:` and `command_line` will always be the highest priority scopes, giving users the ability to completely override a configuration, if need be.

2025-08-15 09:31 UTC, tgamblin commented
I do not think we need something (very) new or separate to accomplish what is described in @alalazo's comment above. I think `include.yaml` is this file... but it can be usable in multiple scopes -- not just in the one special place.  I took a stab at doing this with includes in #51162, which I think is ultimately more flexible -- see there for details.

2026-01-09 20:36 UTC, becker33 requested changes

2026-01-09 20:36 UTC, becker33 commented on etc/spack/defaults/base/concretizer.yaml
> +# section to an environment.
```suggestion
# `~/.config/spack/concretizer.yaml`, by adding a `concretizer:`
# section to an environment, or by using any other Spack scope
# to modify concretizer config. See https://spack.readthedocs.io/en/latest/configuration.html
```
I don't think we should advocate for using the top-level `spack` scope, the `site` scope is preferable, but explaining the differences is probably outside the scope of this comment.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/util/path.py
> +    import spack.paths_base
It would be great to avoid introducing additional imports from `spack.util` into `spack`. Long term, we will need to eliminate all of them.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/util/path.py
> +        "default_download_root": lambda: paths.default_fetch_cache_path,
I don't like having these opaque values for defaults, is this just designed as a placeholder to prevent needing a behavior where the config says one thing but the behavior does another for backwards compatibility? I'm not sure I have a good solution here though.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +To override this behavior, define ``SPACK_USER_CONFIG_PATH`` to be the desired path.
```suggestion
To override this behavior, define ``SPACK_CONFIG_HOME`` to be the desired path.
```
We should update this to match the rest of the variables, and only maintain `SPACK_USER_CONFIG_PATH` as an alias for backwards compatibility.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +This configuration is set in ``$(prefix)/etc/spack/defaults/darwin/packages.yaml``, which is included as by ``$(prefix)/etc/spack/defaults/include.yaml``.
```suggestion
This configuration is set in ``$(prefix)/etc/spack/defaults/darwin/packages.yaml``, which is included by ``$(prefix)/etc/spack/defaults/include.yaml``.
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +* Environment management: ``$spack/var/spack/environtments`` or ``$XDG_DATA_HOME/spack/environments``
We need to update these to not default into the Spack instance (unless the new location is unused and the old one is used, for backwards compatibility).

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +If they are defined, they are used directly without any additional suffix.
We should rephrase this to make the initial statement not seem to contradict the suffixing clarification later. Maybe something like

```suggestion
Spack also includes the variables ``SPACK_DATA_HOME``, ``SPACK_CONFIG_HOME``, and ``SPACK_STATE_HOME`` that override the XDG variables described above.
They work the same way, but have higher precedence than the XDG variables.
If the Spack-specific environment variables *are not* defined, Spack will uses the XDG variables with a suffix of "/spack" to define ``$spack_state_home``, ``$spack_data_home``, and ``spack_cache_home``.
If they are defined, they are used directly without any additional suffix.
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/environments.rst
> +The directory ``$SPACK_ROOT/opt/data/environments/myenv`` is created to manage the environment.
We need to move this default out of the Spack prefix.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/mirrors.rst
> +The mirror is maintained locally (within the Spack installation directory) at :file:`$spack/opt/data`.
This needs to move outside of the Spack prefix

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/repositories.rst
> +For more on the YAML format, and on how configuration file precedence works in Spack, see :ref:`configuration <configuration>`.
```suggestion
Spack uses the ``repos`` config section to find repositories.
Note that the ``repos.yaml`` configuration file is distinct from the ``repo.yaml`` file in each repository.
For more on the YAML format, where configuration files live, and on how configuration file precedence works in Spack, see :ref:`configuration <configuration>`.
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/config.py
> +    site_admin_path = os.path.join(spack.paths_base.etc_path, "site-admin")
This does not require builtin support for Spack to enable, and we shouldn't be proliferating config scopes like this.

Without any changes, admins can already define a scope via config, set it as optional, and set the permissions on it to any value they prefer. The config will only be used by users who have access to read it.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/environment/environment.py
> +default_env_path = lambda: paths.default_envs_path
Why does this need to be a method instead of a value?

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/llnl/util/lang.py
> +                raise Exception("AttrbuteError during creation of Singleton instance") from e
I think this should be factored out as a small unrelated bugfix/debugging helper PR.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/trace.py
> +        raise ValueError(f"Cannot detect writes for Python {sys.version_info[:2]}")
```suggestion
        raise ValueError(f"Cannot detect writes for Python {sys.version_info[:2]} (supported in 3.8 and later)")
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/trace.py
> +        if abs_path.startswith(paths_base.prefix) and intent_to_modify:
Probably need to resolve both of these before comparing, and the same in the rest of this method

2026-01-09 20:36 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +    # $spack/opt/spack
```suggestion
    # $SPACK_DATA_HOME/installs
    # $XDG_DATA_HOME/spack/installs
    # ~/.local/share/spack/installs  # If it already has installs in it
    # $spack/opt/spack # If it already has installs in it
    # ~/.local/share/spack/installs
```

There are a bunch of other files that refer to `$spack/data/installs` or variants thereof that need to be modified to reflect the information here as well, I'm not commenting on all of them to keep this review easier to read.

2026-01-09 20:36 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +  # environments_root: $default_envs_root
```suggestion
  # If set to a non-default value, this setting has precedence.
  # This default value tells spack to check (in order of precedence):
  # $SPACK_DATA_HOME/environments
  # $XDG_DATA_HOME/spack/environments
  # ~/.local/share/spack/environments # if it is already used
  # $spack/var/spack/environments  # if it is already used
  # ~/.local/share/spack/environments
  environments_root: $default_envs_root
```

2026-01-09 20:36 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +  # $spack/var/spack/cache
```suggestion
  # If set to a non-default value, this setting has precedence.
  # This default value tells spack to check (in order of precedence):
  # $SPACK_DATA_HOME/downloads
  # $XDG_DATA_HOME/spack/downloads
  # ~/.local/share/spack/source_cache
```

2026-01-09 20:36 UTC, becker33 commented on etc/spack/defaults/base/modules.yaml
> +    # $user_cache_path/modules/{modules/lmod} otherwise
```suggestion
    # $spack_cache_home/modules/{modules/lmod} otherwise
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/config_yaml.rst
> +These settings can be overridden in ``etc/spack/config.yaml``, or ``~/.config/spack/config.yaml``, or ``~/.config/spack/$spack_instance_id/config.yaml``.
```suggestion
These settings can be overridden in ``etc/spack/config.yaml``, or ``~/.config/spack/config.yaml``.
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/docs/config_yaml.rst
>     config:
The docs need the same explanation that's already in the defaults config regarding how the `$default*` values are evaluated.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/test/cmd/commands.py
> +    # command to omit that.
```suggestion
    # TODO: if someone runs `spack commands --update-completion` when a non-default
    # scope is available, it will be added to the autocompletion scripts, and
    # cause a discrepancy with the runner; it might be worth changing the update
    # command to omit that.
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +    assert p4.default_install_location == str(pathlib.Path(xdg_data_home) / "spack" / "installs")
I think this relationship is probably incorrect, I don't think `XDG_DATA_HOME` should override a configured `config:locations:data`, since the Spack config is more specific.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +    assert p1.package_repos_path == str(pathlib.Path(redirect_usr_cache) / "package_repos")
These 4 tests should check both the old `SPACK_*_PATH` and new `SPACK_*_HOME` environment variables

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +def test_gpg_only_use_new_path_if_old_is_empty(working_env, tmp_path):
This should also test that the new path is used if neither is empty (if you have old and new already used, keep using new).

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/test/conftest.py
> +    saved = spack.paths._unset_xdg_vars(os.environ)
This feels weird that it's returning the prior value instead of the new value. I think it's easier to read as
```suggestion
    saved = os.environ.copy()
    spack.paths._unset_xdg_vars(os.environ)
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/schema/config.py
> +                    "disable_env": {"type": "boolean"},
I may have missed it as this was a lot to review, but I don't see documentation for the `disable_env` config value.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        self.prefix = _prefix or str(PurePath(spack.llnl.util.filesystem.ancestor(__file__, 4)))
```suggestion
        #: This file lives in $prefix/lib/spack/spack/__file__
        self.prefix = _prefix or str(PurePath(spack.llnl.util.filesystem.ancestor(__file__, 4)))
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        self.analyzers_path = os.path.join(self.module_path, "analyzers")
It doesn't look like this path exists, nor is it used anywhere in the code

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        self.repos_path = os.path.join(self.var_path, "repos")
This value is not accurate anymore -- fortunately it also doesn't appear to be used anywhere.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        )
These should respect the `disable_env` config, and their defaults should probably be expressed in terms of the other new config values

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        self.default_xdg_cache_home = os.path.join("~", ".cache", "spack")
I don't think this value is necessary nor used, but I could be missing it somewhere.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +    return saved
I had a comment somewhere else about not liking the design of this. I had a new thought about it, if we want to keep the current design we should rename it to `_pop_xdg_vars`, which will make clearer what to expect for a return value and why the returned values are sufficient to restore state.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +            ["SPACK_USER_CACHE_PATH", "SPACK_STATE_HOME"],
The new variable should be higher priority than the old one.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +            spack_home_cfg_check,
```suggestion
            spack_env_check,
            spack_home_env_check,
            cfg_check,
            spack_home_cfg_check,
            xdg_env_check,
```
I think this reflects the priority order we should use, but it might be worth setting some time to talk specifically about that issue once we're dialed in on the rest of this.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +            return new_location
```suggestion
    def _fallback_old_location_if_used(self, old_location, new_location):
        # TODO: perhaps it should be configurable whether old locations
        # are used. Other option is to relocate downloads & gpg keys.
        if dir_is_occupied(new_location):
            return new_location
        elif dir_is_occupied(old_location):
            # TODO: should probably raise a deprecation warning here encouraging them to set their config explicitly back to the old value
            # that will allow us to eventually remove these fallbacks
            return old_location
        else:
            return new_location
```

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
We probably don't need `default_*` variables for ones that aren't conditional, right? Can't we just use `$spack_state_home/bootstrap` in the config instead of this? This probably applies to a few of the others as well.

2026-01-09 20:36 UTC, becker33 commented on lib/spack/spack/paths.py
> +    return os.path.expanduser(val)
I think this method might be vestigial since you implemented the more complicated `resolve_a_home` method.

2026-01-10 02:28 UTC, scheibelp commented on lib/spack/spack/environment/environment.py
> +default_env_path = lambda: paths.default_envs_path
This avoids having to resolve it at module import time

2026-01-12 22:20 UTC, scheibelp commented on lib/spack/spack/util/path.py
> +    import spack.paths_base
> avoid introducing additional imports from spack.util into spack

I think you are saying we should avoid all cases where we have a module in `spack.util.*` that  does `import spack.not_util.*`

I think that goal can only be achieved by moving `canonicalize_path` (and supporting functions) out of this module (and into `spack.not_util`). Do you want me to pursue that as part of this PR?

2026-01-12 22:43 UTC, scheibelp commented on etc/spack/defaults/base/concretizer.yaml
> +# section to an environment.
I'm worried about default suggestions that don't isolate spack instances. The direct way to do that would be to suggest `site` first here, vs. `spack`; I hope though that I can entirely avoid disagreement here by avoiding any scope suggestions at all (I think that would be ideal here because pretty much any config a user manages to include will override defaults).

2026-01-12 23:00 UTC, scheibelp commented on lib/spack/docs/configuration.rst
> +To override this behavior, define ``SPACK_USER_CONFIG_PATH`` to be the desired path.
Apologies but `SPACK_CONFIG_HOME` no longer exists and I think it would actually be misleading for it to exist (would imply there's a similar fall-through path for config as for data/cache/state). I'll be trying to update the docs more, but this is sufficiently-in-flux enough that at the moment my focus is keeping the PR description as definitive, and then updating docs if we agree as part of preliminary review.

2026-01-12 23:34 UTC, scheibelp commented on lib/spack/spack/config.py
> +    site_admin_path = os.path.join(spack.paths_base.etc_path, "site-admin")
I was under the impression if a config scope exists but that the Spack instance does not have sufficient permissions to access it, that it would cause a failure in Spack. If that is true, then I think this particular item is worth more discussion. I think you may be right that each user of site-installed spack may be able to come up with their own solution to the problem this is trying to address, but I was hoping I could mostly solve it for them.

2026-01-13 08:11 UTC, scheibelp commented on lib/spack/spack/paths_base.py
> +        )
By the time the true value of `disable_env` is known, this scope will have (or can have) been read in from the path specified by this variable. I recommend keeping all semantics related to processing of the config itself env-variable based (and there is already SPACK_DISABLE_LOCAL_CONFIG for that).

We could process all scopes above spack into a config, then use it to make these sorts of decisions, but I think that would add more complication than is needed (IMO providing one toggle to either turn these scopes on or off is sufficient).

Another example: see `env_based_state_home` added in https://github.com/spack/spack/pull/47615/commits/a7fd5decdc10e1bac66a32ce382e18fecf48d355 for more context, used for the config include cache.

2026-01-13 18:58 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
Question: there are pre-existing `default_` variables and I think the general pattern for those was that `spack.paths` was a centralized spot to record configuration fallback defaults. A few other variables like this are:

- `default_test_path`
- `default_misc_cache_path`
- `default_license_dir`

`default_monitor_path` is not used in this way (or anywhere, but is pre-existing)

I removed this one you pointed out, but I think it might actually be useful to preserve this behavior: maybe I could distinguish the variables like `default_install_location`/`default_envs_path` from (e.g.) `default_test_path`? 

* They *are* somewhat-aligned in the sense that config vars completely override them. 
* Or perhaps the primary distinction for you is that they potentially redirect to old spack locations (so perhaps `preferred_` vs. `default_` for the install/envs paths?)

2026-01-13 20:11 UTC, scheibelp commented on etc/spack/defaults/base/config.yaml
> +    # $spack/opt/spack
I have eliminated all such references from the config defaults and from the docs.

2026-01-13 20:12 UTC, scheibelp commented on lib/spack/docs/config_yaml.rst
>     config:
(EDIT) I have now added a section in `configuration.rst`: "Spack-specific variables controlling data location"

2026-01-13 20:14 UTC, scheibelp commented on lib/spack/docs/configuration.rst
> +If they are defined, they are used directly without any additional suffix.
I rewrote this section (among other things the rewrite reflects that config file vars like `$spack_state_home` no longer exist in this PR): `configuration.rst` - "Spack-specific variables controlling data location"

2026-01-13 21:35 UTC, scheibelp commented on lib/spack/spack/test/paths.py
> +    assert p1.package_repos_path == str(pathlib.Path(redirect_usr_cache) / "package_repos")
Apologies but I'm not clear on which 4 you mean, I have an incoming change that will update this one specifically. The other two `_overridable` tests concern config which don't have alternate variables and don't follow the fall-through pattern for `spack_data`.

Specifically I extended this test to check the environment var precedence that exists just for `SPACK_STATE_HOME`/`SPACK_USER_CACHE_PATH` (IMO test_install_location covers the rest of the fall-through logic, though I could check that here as well if desired).

2026-01-13 21:52 UTC, scheibelp commented on lib/spack/spack/schema/config.py
> +                    "disable_env": {"type": "boolean"},
Incoming commit will add section for this to `config_yaml.rst`

2026-01-13 21:53 UTC, scheibelp commented on lib/spack/spack/paths_base.py
> +        self.analyzers_path = os.path.join(self.module_path, "analyzers")
I'll remove it, but FYI this path existed before this PR

2026-01-14 01:05 UTC, scheibelp commented on lib/spack/spack/paths.py
> +            spack_home_cfg_check,
Incoming commit will update this. I am collapsing the related comment in the test (https://github.com/spack/spack/pull/47615#discussion_r2677469900): I can update the test based on what is decided here.

2026-01-14 07:56 UTC, scheibelp commented on lib/spack/spack/llnl/util/lang.py
> +                raise Exception("AttrbuteError during creation of Singleton instance") from e
https://github.com/spack/spack/pull/51845

2026-01-14 22:17 UTC, becker33 commented on etc/spack/defaults/base/concretizer.yaml
> +# section to an environment.
I'm fine with not suggesting a scope at all

2026-01-14 22:33 UTC, becker33 commented on lib/spack/spack/config.py
> +    site_admin_path = os.path.join(spack.paths_base.etc_path, "site-admin")
That appears true, but that is due to a bug in how we handle optional scopes. I think we should fix that bug instead of adding an entire scope to work around it.

I think we should view adding yet-another-scope to Spack as a very large negative of any solution that it comes up for.

2026-01-14 22:35 UTC, becker33 commented on lib/spack/spack/llnl/util/lang.py
> +                raise Exception("AttrbuteError during creation of Singleton instance") from e
Merged

2026-02-05 20:27 UTC, becker33 requested changes

2026-02-05 20:27 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +  # environments_root: $default_envs_root
This should probably not be commented out -- none of the other defaults that replicate the code default are.

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/chain.rst
> +      install_tree: /path/to/another/dir/containing/.spack-db
```suggestion
    install-tree-1:
      install_tree: /path/to/other/dir/containing/install/tree
    install-tree-2:
      install_tree: /path/to/another/dir/containing/install/tree
```

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/chain.rst
> +The ``install_tree`` must point to a directory containing ``.spack-db``, for example ``install_tree`` defined in :ref:`config.yaml <config-yaml>`.
```suggestion
The ``install_tree`` must point to a directory containing a spack install tree, as defined in :ref:`config.yaml <config-yaml>`.

.. note:
   
   The ``install_tree`` directory is the directory containing the ``.spack-db`` hidden directory. This can be used to confirm you have the correct directory level listed for your upstream.
```

I think we should define this in terms of the configured directory, not in terms of the hidden directory that they shouldn't ever need to think about. I've retained the reference as a note to help them confirm.

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +  Prefers ``$data_home/installs``, but if there are no installs there but there are installs in the old location within ``$spack``, then the old location will be used.
```suggestion
  Prefers ``$data_home/installs``, but if there are no installs there and there are installs in the old location ``$spack/opt/spack``, then the old location will be used.
```

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +  Prefers ``$data_home/envs`` but if there are no envs there and there are envs in the old location in ``$spack``, then the old location will be used.
```suggestion
  Prefers ``$data_home/envs`` but if there are no envs there and there are envs in the old location ``$spack/var/spack/environments``, then the old location will be used.
```

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/environments.rst
> +  ==> Updating view at ~/spack/opt/data/environments/myenv/.spack-env/view
Why is this in `$spack/opt/data`? Is this leftover from a previous draft of the PR?

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/mirrors.rst
> +Adding a mirror really adds a line in ``~/.config/spack/mirrors.yaml``:
```suggestion
Adding a mirror really adds an entry in the mirrors config, by default stored in the user environment scope at ``~/.config/spack/mirrors.yaml``:
```

2026-02-05 20:27 UTC, becker33 commented on lib/spack/docs/mirrors.rst
> +The mirror is maintained locally (within the Spack installation directory) at :file:`$data_home/downloads`.
```suggestion
The mirror is maintained locally at :file:`$data_home/downloads`.
```

2026-02-05 20:27 UTC, becker33 commented on lib/spack/spack/bootstrap/config.py
> +        spack.config.get("bootstrap:root", "$user_cache_path/bootstrap")
```suggestion
        spack.config.get("bootstrap:root", "$cache_home/bootstrap")
```

2026-02-05 22:50 UTC, scheibelp commented on lib/spack/spack/bootstrap/config.py
> +        spack.config.get("bootstrap:root", "$user_cache_path/bootstrap")
I think replacing `$user_cache_path` with `$state_home` (vs. `$cache_home`) will be what you want: `user_cache_path` is a stand-in for `$SPACK_/XDG_STATE_HOME`; in XDG, cache_home is for things that can be deleted after log-out, state-home is for things that can be deleted whenever, but are convenient to keep between logins.

2026-02-09 21:57 UTC, scheibelp commented on lib/spack/docs/chain.rst
> +The ``install_tree`` must point to a directory containing ``.spack-db``, for example ``install_tree`` defined in :ref:`config.yaml <config-yaml>`.
Upcoming commits will remove references to `.spack-db`, but I think there has to be a precise way to tell users what their install dir is, so I added `spack location --install-root` (the doc then says to do this or `spack config get config`, as before this PR that wouldn't work).

(I collapsed the other comment since I think we can track this in one convo)

2026-02-10 06:55 UTC, scheibelp commented
Not quite done, but newest edits include:

- `spack location --install-root`: helps with the documentation about how to set up upstreams
- `bypassed_old_envs_warning`: the store/environment singleton methods for accessing default install/env paths will report a warning once per Spack process if installs/environments are detected in their old location but not used
    - There are some conditions where this warning is not printed, e.g. if the user sets SPACK_DATA_HOME it is assumed they are aware of the new default install location. This is primarily for if a new spack instance writes into the new default install location in ~, and then an old (pre-this-PR) instance of spack advances its commit to a point where this location would override it (after this PR)
- (EDIT Feb 23 2026): for build subprocesses, I updated `subprocess_context` to "freeze" the value of `spack.paths.*` variables by accessing them immediately when initializing the subprocess (before XDG_* variables would be set by package recipes). This replaces the approach that adds highest-precedence env vars.
- ~Install subprocess management: env vars controlling paths could potentially be interfered with by package definitions (if they set/unset XDG_DATA_HOME, for example) - the PR creates a set of env vars that have highest priority and are explicitly used to communicate parent process settings to subprocesses~
    - Another option might be passing a temporary config scope (although technically all config is lower priority than env vars, it is higher than XDG)

2026-02-12 06:30 UTC, scheibelp commented
- pipelines in my PR will fail unless spack-packages is modified to accommodate the possibility that indices can live somewhere else (e.g. https://github.com/spack/spack-packages/blob/develop/.ci/gitlab/configs/ci.yaml has `touch ${SPACK_USER_CACHE_PATH}/cache/*/*`, which fails and truncates the before/middle scripts in my PR - b98dbf630d709567abd76a35a1100fa423a89307 and 898e9321c04474c509ddbe2ef0b6ad7cfb90c2b5 temporarily undo the spack_instance_id logic).
- As it is, I made the `include` config in the `spack` scope base the `user` scope on `spack_home`  if the user sets config:locations:home in a *lower* scope, then it will be seen (generally speaking a scope and everything it includes can access the config of all lower scopes)
    - IMO we should add a scope inside of $spack that is explicitly for setting these locations, and is processed before (i.e. at a lower level) than the `spack` scope group (i.e. it cannot be included by the `spack` scope)

2026-03-05 19:55 UTC, becker33 requested changes

2026-03-05 19:55 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> -  # - $spack/var/spack/stage
This commented-out line should be removed

2026-03-05 19:55 UTC, becker33 commented on etc/spack/include.yaml
> +    path: "$spack_home/.config/spack/"
We should probably have a comment here explaining which methods of setting `$spack_home` affect this and which ones do not. IIRC the config methods don't affect it, but $XDG_HOME and $SPACK_HOME do, is that right?

2026-03-05 19:55 UTC, becker33 commented on lib/spack/docs/chain.rst
> +      install_tree: /path/to/old/spack/opt/spack
```suggestion
      install_tree: /path/to/yet/another/spack/install/tree
```
I don't want to preserve references to the old format where we don't need them, since hopefully eventually it will be long-forgotten.

2026-03-05 19:55 UTC, becker33 commented on lib/spack/docs/configuration_basics.rst
> +#. Under the default for ``XDG_DATA_HOME``: ``~/.local/share/spack``
```suggestion
#. ``SPACK_DATA_HOME`` env var if that is set
#. ``SPACK_HOME/share/spack`` if the ``SPACK_HOME`` env var is set
#. ``config:locations:data``
#. ``config:locations:home/share/spack``
#. ``XDG_DATA_HOME/spack`` if the ``XDG_DATA_HOME`` env var is set
#. Under the default for ``XDG_DATA_HOME``: ``~/.local/share/spack``
```

I think I've edited this to be accurate, but can you confirm?

1. This is what we agreed on
2. The code matches this

2026-03-05 19:55 UTC, becker33 commented on lib/spack/docs/configuration.rst
> +  Prefers ``$data_home/installs``, but if there are no installs there but there are installs in the old location ``$spack/opt/spack``, then the old location will be used.
```suggestion
  Prefers ``$data_home/installs``, but if there are no installs there and there are installs in the old location ``$spack/opt/spack``, then the old location will be used.
```

2026-03-05 19:55 UTC, becker33 commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "cache")
Do we need a `default_*` value for this, since it doesn't have the sort of complex logic that motivates the others?

2026-03-05 19:55 UTC, becker33 commented on lib/spack/spack/paths.py
> +
```suggestion
        def _env_check(relpath, provenance):
            if disable_env:
                return
            if isinstance(env_vars, str):
                x = [env_vars]
            else:
                x = env_vars
            for n in x:
                if n in os.environ:
                    return os.path.join(os.environ[n], relpath), provenance
```
And then we can add the args to each of the checks instead of having so many separate methods. I think we could do the same to unify the config methods

2026-03-05 19:55 UTC, becker33 commented on lib/spack/spack/test/cmd/commands.py
> +        assert False, msg
If it's easy to factor this out as a separate PR that would make sense, but if not I don't want to hold this up over it.

2026-03-05 19:55 UTC, becker33 commented on lib/spack/spack/config.py
> +    site_admin_path = os.path.join(spack.paths_base.etc_path, "site-admin")
I still think we need to remove this scope.

2026-03-05 19:55 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +    def env_based_state_home(self):
As discussed offline, can you try to change how `include_cache_location` is used to eliminate the need for this and instead create a temporary stage for downloaded config files in tmpdir, so that we can read them to know where to put them?

2026-03-06 00:58 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "cache")
No: this variable predates this PR. Generally I preserve variables that existed before this PR. Do you think it should be removed? I think that would actually probably clarify things because the default configs don't refer to a config var based on this, and e.g. https://github.com/spack/spack/pull/50920 did not end up reverting the spack-id-based misc cache path defined in `paths.py` because it is always controlled by default configs.

2026-03-06 02:01 UTC, scheibelp commented on lib/spack/docs/configuration_basics.rst
> +#. Under the default for ``XDG_DATA_HOME``: ``~/.local/share/spack``
Two differences from what you have: 

* `SPACK_HOME/.local/share/spack` when using SPACK_HOME env var
* likewise `config:locations:home/.local/share/spack` when using that config var

the env var case was not enforced w/ the unit tests, so I'm going to update that too.

2026-03-06 02:04 UTC, scheibelp commented on lib/spack/spack/paths.py
> +
I've now done this refactor. It doesn't save many lines, but the consolidation probably helps with clarity.

2026-03-06 03:08 UTC, scheibelp commented on etc/spack/include.yaml
> +    path: "$spack_home/.config/spack/"
I think we agreed when talking today that we should avoid any references to location variables in `include:` config, this is back to `~/.config/spack/`, and if the user wants to consolidate everything including a user config scope under one dir they can do e.g.

```
config:
  locations:
    home: foo
include:
- name: "user"
  path: foo/config
```

2026-03-06 06:10 UTC, scheibelp commented on lib/spack/spack/test/cmd/commands.py
> +        assert False, msg
https://github.com/spack/spack/pull/52032

2026-03-06 19:28 UTC, scheibelp commented on lib/spack/spack/paths_base.py
> +    def env_based_state_home(self):
We agreed this can be removed entirely when https://github.com/spack/spack/pull/51896 lands (at which point there will be no dedicated config include cache directory, and no need for this variable).

2026-03-07 01:12 UTC, scheibelp commented on lib/spack/spack/config.py
> +    site_admin_path = os.path.join(spack.paths_base.etc_path, "site-admin")
Latest commits have removed `site-admin`. I was thinking about it and added some examples to the PR description about how some administrative use cases related to managing upstreams/permissions can be handled with `include:`.

2026-03-09 21:27 UTC, becker33 commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
I think I was conflating exposing these as config variables with having accessors for them in `spack.paths`. I'm fine with leaving them in `spack.paths`, but they should not be exposed as config vars. I would also prefer that if they have only one call site and are straightforward/obvious names, they should be inlined, but I don't think it's worth major effort to track them down to standardize that, only if you have to make a decision.

2026-03-09 21:31 UTC, becker33 commented on lib/spack/spack/paths_base.py
> +        )
I don't think that relying entirely on environment variables is sufficient, but luckily we also have the `include` config by which we can affect this as well. We can provide porcelain commands like `spack isolate` that remove the environment-dependent behavior from the include config in addition to setting `disable_env`.

I'm going to mark this as resolved, I agree we should not be making a change in the code here.

2026-03-09 21:38 UTC, becker33 commented on lib/spack/spack/util/path.py
> +    import spack.paths_base
I think we need to do that eventually, but I think this PR is not making the problem worse so it's worth keeping it orthogonal.

2026-03-09 21:40 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +    os.environ.update(saved)
This might be cleaner if you use the `working_env` fixture instead of separately restoring.


```suggestion
@pytest.fixture(scope="module", autouse=True)
def clear_env_vars(working+env):
    spack.paths_base._unset_xdg_vars(os.environ)
    for x in [
        "SPACK_USER_CACHE_PATH",
        "SPACK_HOME",
        "SPACK_DATA_HOME",
        "SPACK_STATE_HOME",
        "SPACK_CACHE_HOME",
    ]:
        os.environ.pop(x, None)
```

2026-03-09 21:41 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +        os.environ["HOMEPATH"] = val
```suggestion
        os.environ["HOMEPATH"] = val
```

2026-03-09 21:43 UTC, becker33 commented on lib/spack/spack/test/paths.py
> +    assert p1.package_repos_path == str(pathlib.Path(redirect_usr_cache) / "package_repos")
I think that the other changes to this PR since we first talked make this irrelevant besides the change you already made.

2026-03-10 00:47 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
> I think I was conflating exposing these as config variables with having accessors for them in spack.paths. I'm fine with leaving them in spack.paths, but they should not be exposed as config vars.

OK, confirming that these do not have associated config vars

>  I would also prefer that if they have only one call site

Ok now that is true (originally was not true for `default_license_dir`, but now is)

> and are straightforward/obvious names, they should be inlined, 

Sorry I'm not sure what each of these mean: 
* Does "straightforward/obvious" just mean that they aren't that now and I should be coming up with new names? * "inlining" could mean you simply find it odd there is a dedicated property defined here, vs. defining it in __init__, but anything that depends on `*_home` vars (data/state/cache) has to be a property to keep it lazy (i.e. not defined at `__init__` time)

2026-03-10 01:50 UTC, becker33 commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
e.g. if the variable is `default_bootstrap_root` and it's just joining `state_home` with `"bootstrap"`, maybe inline it, but if there's complex logic or a reason the path reads very differently from the variable name, it's worth keeping separate.

By inlining, I mean if there's only one call site, do the join there. E.g.

```
"license_dir": os.path.join(spack.paths.data_home, "licenses")
```

All that to say, I think given they don't have config vars associated with him it's not worth spending more time on this.

2026-03-11 23:10 UTC, becker33 commented on lib/spack/docs/configuration_basics.rst
> +Spack-specific variables controlling data location
This section should probably cover `spack_home` as well. It may also be worth a note mentioning that config is controlled through the `include` section instead because of the issue with self-referential config scopes.

2026-03-11 23:10 UTC, becker33 commented on etc/spack/defaults/base/config.yaml
> +  # updated to tolerate this relocation of misc caches
This comment should be removed now that the code has caught up with it.

2026-03-11 23:16 UTC, scheibelp commented on lib/spack/spack/paths.py
> +        return os.path.join(self.state_home, "bootstrap")
Recent commits have since done this inlining, so I'll mark this as resolved

2026-03-26 23:17 UTC, becker33 requested changes
A couple more things I found while looking through this with @tgamblin showing him how it's all implemented.

2026-03-26 23:17 UTC, becker33 commented on lib/spack/spack/paths.py
> +user_config_path = locations.user_config_path
```suggestion
```
We can delete all of these, and in `lib/spack/spack/package.py` we can change from `from spack.paths import spack_script` to

```
import spack.paths
spack_script = spack.paths.locations.spack_script
```

2026-03-26 23:17 UTC, becker33 commented on lib/spack/spack/paths.py
> +                path is appended to the result to get the component location.
This order needs to change to reflect the changes we made.

2026-03-26 23:17 UTC, becker33 commented on lib/spack/spack/trace.py
> +def _guard_writes(event, args):
[Not for this PR] We should extend this to allow for a check that `spack isolate` is working properly as well.

2026-03-27 22:46 UTC, scheibelp commented on lib/spack/spack/paths.py
> +                path is appended to the result to get the component location.
I have updated the parameter order but it does not fully align with resolution order: for example home_rel is used for both `$SPACK_HOME` and `config:locations:home`, but `$SPACK_HOME` is higher priority than `config:locations:data` and lower than `$SPACK_DATA_HOME` (i.e. the "middle two" parameters could be either order, but at this point the first and last align). I have also updated the docstring to discuss location precedence (that wasn't described in a docstring in this module so it seemed useful to do that).

2026-04-07 06:10 UTC, becker33 requested changes

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree ~/.local/state/spack/bootstrap/store
```suggestion
          tree $(spack bootstrap root)
```
This is more future-proof if we change the bootstrap store in ci, I don't know if that matters.

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree ~/.local/state/spack/bootstrap/store
ditto

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree ~/.local/state/spack/bootstrap/store
ditto

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree ~/.local/state/spack/bootstrap/store
ditto

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree ~/.local/state/spack/bootstrap/store
ditto

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree $env:userprofile/.local/state/spack/bootstrap/store
I suspect that would work here as well, but I don't know the windows support as well as you do.

2026-04-07 06:10 UTC, becker33 commented on .github/workflows/bootstrap.yml
> +          tree $env:userprofile/.local/state/spack/bootstrap/store
ditto

2026-04-07 06:10 UTC, becker33 commented on etc/spack/defaults/base/modules.yaml
> +     tcl:    $modules_base/modules
I thought last we discussed `modules_base` doesn't need to be a fancy variable and they can just be set to `$data_home/modules` and `$data_home/lmod`?

2026-04-07 06:10 UTC, becker33 commented on etc/spack/include.yaml
> +    path: "~/.config/spack/"
I think this is the highest impact change that we don't have a backwards compatibility mitigation for at the moment. This will silently ignore people's existing configs.

We should consider e.g. having a `backwards-compat` scope in Spack 1.2 (removed in v1.3) that uses `~/.spack`

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/config_yaml.rst
> +The additional flag setting ``locations:disable_env`` will prevent environment variables from influencing these locations.
This should include a link to where the docs talk about the environment variables that can override these values.

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/configuration_basics.rst
> +#. Under ``SPACK_HOME`` env var; for ``$data_home``, it is this plus ``.local/share/spack``
```suggestion
#. Under ``SPACK_HOME`` env var; for ``$data_home``, it is ``$SPACK_HOME/.local/share/spack``
```

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/configuration_basics.rst
> +#. Under ``config:locations:home``; for ``$data_home`` it is this plus ``.local/share/spack``
```suggestion
#. Under ``config:locations:home``; for ``$data_home`` it is ``$spack_home/.local/share/spack``
```

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/configuration_basics.rst
> +* Config file locations are an exception: they can only be controlled with :ref:`environment variables <local-config-overrides>` or with :ref:`include.yaml <include-yaml>`
It would be great if we could format this into a table with an exhaustive list of all the data written into each of these locations, so we could use it as a reference guide for where the default is for each configurable location.

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/developer_guide.rst
> +                              Can be overridden by files in ~/.config/spack.
This isn't true anymore, `$spack/etc/spack` is higher priority than `~/.spack`, which is in turn higher than the rest of the files in `$spack/etc/spack/...`.

Suggestion: we just remove this line entirely.

```suggestion
```

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/environments.rst
> +The directory ``$data_home/envs/myenv`` is created to manage the environment.
Why are we changing from `environments` to `envs`? For this, I think I'd prefer `$data_home/environments` as the default (modulo all the logic we've talked about for backwards compatibility of the default directory).

2026-04-07 06:10 UTC, becker33 commented on lib/spack/docs/where_spack_writes_data.rst
> +For more on this, see:
```suggestion
In the absence of any Spack-specific settings, Spack will respect [XDG](https://specifications.freedesktop.org/basedir/latest/) environment variables controlling the home directory for specific types of data.

For more on this, see:
```

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/solver/core.py
> +                    spack.config.CONFIG.get("bootstrap:root", "$user_cache_path/bootstrap")
```suggestion
                    spack.config.CONFIG.get("bootstrap:root", "$cache_home/bootstrap")
```

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/test/cmd/commands.py
> +def test_updated_completion_scripts(shell, tmp_path: pathlib.Path, mutable_config):
Is there a reason this needs to be mutable? I think 
```suggestion
def test_updated_completion_scripts(shell, tmp_path: pathlib.Path, config):
```
should work

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/util/path.py
> +        raise ResolutionContextError(self.var)
These look like they're vestigial after other changes.

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/cmd/isolate.py
> +# Copyright Spack Project Developers. See COPYRIGHT file for details.
Can you move isolate and the associate tests to a separate PR?

1. This is already huge
2. I have comments on `spack isolate` that are independent of this PR
3. The docs will need further updates to account for `spack isolate` that aren't in this PR yet, and I don't want to hold it up and put you in rebase hell.

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +    def _bypass_warning(self, chosen_path, old_path, data_category, cfg_settings, _show=True):
I find the name of this method confusing, because it suggests that the method bypasses a warning.

Can we rename it to something more descriptive like `_warn_on_unused_old_data` (don't feel strongly about that name, just don't like using a noun that can also be a verb in a method name)?

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +            self._state_home, self._state_home_provenance = self.resolve_a_home(
```suggestion
            self._state_home, _ = self.resolve_a_home(
```
_state_home_provenance is never used

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +            self._cache_home, self._cache_home_provenance = self.resolve_a_home(
```suggestion
            self._cache_home, _ = self.resolve_a_home(
```
_cache_home_provanence is never used

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +        return self._data_home
```suggestion
    @property
    def data_home(self):
        if not self._data_home:
            self._data_home, self._data_home_provenance = self.resolve_a_home(
                "SPACK_DATA_HOME", "data", SpackPaths.relative_data_home, "XDG_DATA_HOME"
            )
        return self._data_home
        
    @property
    def data_home_provenance(self):
        if not self._data_home_provenance:
            self._data_home, self._data_home_provenance = self.resolve_a_home(
                "SPACK_DATA_HOME", "data", SpackPaths.relative_data_home, "XDG_DATA_HOME"
            )
        return self._data_home_provenance
```
I think we need a getter property for this value, because otherwise it would be really easy to write a bug by accessing `self._data_home_provenance` before accessing `self.data_home`. Even argument order could matter at that point.

Then all the access points will need to be modified to use it.

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +        )
default_state_home and default_cache_home are never used

2026-04-07 06:10 UTC, becker33 commented on lib/spack/spack/paths.py
> +    def modules_base(self):
See other comment on this variable, I don't think we need it and its (mild) complications.

2026-04-07 16:44 UTC, scheibelp commented on lib/spack/spack/solver/core.py
> +                    spack.config.CONFIG.get("bootstrap:root", "$user_cache_path/bootstrap")
EDIT (this was initially incorrectly worded) (`user_cache_path == state_home`, `user_cache_path != cache_home`; I will change to `state_home` here; this has happened enough times I worry it will be an issue going forward)

2026-04-07 18:23 UTC, scheibelp commented on etc/spack/defaults/base/modules.yaml
> +     tcl:    $modules_base/modules
I must have lost track of it: I think your argument here is that discarding old modules is never a problem because they can be regenerated easily (I've spoken to people who edit spack-generated modules, but I think they always copy them into a new location before doing that). I think that will work.

2026-04-07 18:54 UTC, scheibelp commented on lib/spack/spack/paths.py
> +    def modules_base(self):
I have removed `modules_base`, my recollection from talking to you was that this is fine because detecting and using old modules isn't important (vs. old installs or environments)

I'll resolve https://github.com/spack/spack/pull/47615#discussion_r3041894323, and this can also be resolved if I got that right.

2026-04-07 18:58 UTC, scheibelp commented on etc/spack/include.yaml
> +    path: "~/.config/spack/"
I have added that scope:

```
$ spack config scopes
command_line
spack
user
backwards-compat <--------------
site
system
defaults
defaults:darwin
defaults:base
_builtin
```

2026-04-07 21:22 UTC, scheibelp commented on lib/spack/docs/configuration_basics.rst
> +* Config file locations are an exception: they can only be controlled with :ref:`environment variables <local-config-overrides>` or with :ref:`include.yaml <include-yaml>`
I have added a table at https://spack--47615.org.readthedocs.build/en/47615/where_spack_writes_data.html

also, I ended up moving nearly all discussion of variables like `$data_home` into the new section `Controlling where spack writes data` (configuration basics includes those variables in its list now but doesn't expand on them and just points to this section).

Furthermore I realized the end of `configuration_basics.rst` was still describing the outdated method for isolating spack instances (at the end): I removed it (`Controlling where spack writes data` should cover this).

2026-04-10 22:37 UTC, becker33 requested changes
The way I see it there are two real questions left:

1. What is the best method for mitigating the pain for users for the change to the default user config path?
2. Should `misc_cache` be under `$state_home` or `$cache_home`?

I know we had some substantial conversations about question 2, but I went through all of the comments I could find on this PR and I couldn't find where those conversations were. Sorry to be dragging up something that we moved past a while ago, but luckily once we answer this we can very easily change it if needed.

The rest of the requests in this review are minor additions to the docs.

Overall I think this is very close to ready to merge.

2026-04-10 22:37 UTC, becker33 commented on lib/spack/docs/where_spack_writes_data.rst
> +``config:locations:home`` / ``SPACK_HOME`` can be used to control all 3 of ``data_home``, ``cache_home``, and ``state_home``.
```suggestion
``config:locations:home`` / ``SPACK_HOME`` can be used to control all 3 of ``data_home``, ``cache_home``, and ``state_home``.
For ``data_home``, the default is ``$spack_home/.local/share/spack``.
For ``state_home``, the default is ``$spack_home/.local/state/spack``.
For ``cache_home``, the default is ``$spack_home/.cache/spack``.
```

2026-04-10 22:37 UTC, becker33 commented on lib/spack/docs/where_spack_writes_data.rst
> +
```suggestion
+-----------------+-----------+------------+------------+--------------------+
| misc cache      |           | x [#wheretable-2]_ |            |                    |
+-----------------+-----------+------------+------------+--------------------+
| test stages     |           | x          |            |                    |
+-----------------+-----------+------------+------------+--------------------+
| licenses        | x         |            |            |                    |
+-----------------+-----------+------------+------------+--------------------+
| config files    |           |            |            | x [#wheretable-3]_ |
+-----------------+-----------+------------+------------+--------------------+

.. [#wheretable-1] cache_home is used as a backup, but Spack prefers to write into the users temp dir if it's available
.. [#wheretable-2] The [XDG](https://specifications.freedesktop.org/basedir/latest/) specification requires that ``cache_home`` be removable. Spack caches are intended to be longer-lived, so they live in ``state_home`` instead.
.. [#wheretable-3] as discussed elsewhere in this section, user-scope config is controlled with :ref:`environment variables <local-config-overrides>` or with :ref:`include.yaml <include-yaml>` to avoid recursion issues with configurable locations. For the locations of other config scopes and how to write to them instead, see :ref:`configuration scopes <configuration-scopes>`.

```
I think we either need to do this or move `misc_cache` back into `cache_home` -- I'm going to be going back to older comments and reminding myself why we thought it couldn't be in `cache_home`, because the actual [XDG spec](https://specifications.freedesktop.org/basedir/latest/) doesn't seem to have anything that would be a problem for us to put our cache in cache_home (and that would improve our sanity).

2026-04-10 22:37 UTC, becker33 commented on etc/spack/include.yaml
> +    path: "~/.config/spack/"
I realize we don't have a good way to trigger a deprecation warning based on usage of the backwards-compat scope, so it may be hard to move users off of it. I see three options:

1. Decide we don't need backwards compatibility (I don't like this one at all)
2. Keep the new scope, add some ad-hoc way to trigger a deprecation warning if it's used
3. Remove the backwards-compat scope, and add some manual logic in spack main to warn if `SPACK_USER_CONFIG_PATH` is not set to `~/.spack`, and the user config scope path is not set to `~/.spack`, but the `~/.spack` directory exists and is not empty.

I think I was hasty with my review on Monday, and (3) is probably a better option than (2). What do you think? The primary reason that I prefer it is that I think it will be easier to eventually move away from in the long run (it can emit code for the user to set the user config path for themselves or recommend that they copy those files to `~/.config/spack` to suppress the warning). Then in Spack 1.3 we can remove it entirely.

2026-04-13 04:02 UTC, scheibelp commented on lib/spack/docs/where_spack_writes_data.rst
> +
I'm a big fan of doing this vs. putting `misc_cache` in `cache_home`

The official XDG spec (that you linked) doesn't have much to say about where you put anything (except for `XDG_RUNTIME_DIR` perhaps).

I was using https://wiki.debian.org/XDGBaseDirectorySpecification for guidance (linked in https://github.com/spack/spack/issues/49939) which I think has a very reasonable interpretation about what the categories mean (what is "data"? what is "state"? the table there defines these in terms of their lifetime, space usage, and sync/share requirements); because I find it reasonable, I think we should follow those definitions as well.

2026-04-14 16:01 UTC, becker33 requested changes

2026-04-14 16:01 UTC, becker33 commented on lib/spack/spack/main.py
> +    for scope in cfg.scopes.values():
I don’t think we need a sentinal for the check in main.py — we can just recommend they transfer those configs to the new `~/.config/spack` directory or set `SPACK_USER_CONFIG_PATH` to suppress it. Then the check can just be

1. Is this directory different from the user config scope path
2. Does the directory exist
3. Does it have anything in it

If yes to all three, throw the warning. And the warning should mention that this is deprecated and will be removed in Spack 1.3

------

I also think the same check might be cleaner without the backwards compat scope (because then it would work the same way that it works for installs and environments). We could do

```
def _warn_unused_old_config():
    user_scope = [s for s in cfg.CONFIG.active_scopes() if s.name == "user"]
    if not user_scope:
        return

    new_path = "~/.config/spack"
    if getattr(user_scope[0], "path", "") != new_path:
        # User overrode the scope path, they meant it
        return

    old_path = "~/.spack"
    if os.path.isdir(old_path) and bool(os.listdir(old_path)):
        msg = (
            f"Bypassing config in '{old_path}' in favor of '{new_path}'.\n"
            f"    Detected config in old locations '{old_path}'.\n" 
            f"    Set `SPACK_USER_CONFIG_PATH` or modify your include.yaml to use '{old_path}'\n."
            f"    Or move files from '{old_path}' to '{new_path}' to suppress this warning."
        )
        tty.warn(msg)
```

which is probably the closest to the same behavior as the other new locations as we can get (without some special logic to modify the path of the user scope if the old path exists and the new one does not, which seems overkill).

------

Third option is what I just mentioned to modify the scope on the fly if we detect the old one and the new one is empty (and we could warn the user about that as well).

2026-04-14 19:49 UTC, psakievich commented on lib/spack/spack/main.py
> +    for scope in cfg.scopes.values():
The other case for this is people who have multiple spack instances spanning many versions of Spack. The directory will likely keep getting re-created. I don't know if it is worth engineering for though. For the people who are bothered by ~/.spack, they've been engineering around it for a while. 

I agree with this proposal, and I wouldn't really do too much more. This is a very popular change even if it is more breaking than we wanted for a minor release.

2026-04-14 21:00 UTC, psakievich reviewed
Mainly commented on docs. Overall I think it's cool to see the way this has come together. There's certainly a lot more nuance and detail to this effort than I realized when I first got involved. Major thanks to @scheibelp to keeping with it.

2026-04-14 21:00 UTC, psakievich commented on lib/spack/docs/where_spack_writes_data.rst
> +``config:locations:home`` / ``SPACK_HOME`` can be used to control all 3 of ``data_home``, ``cache_home``, and ``state_home``.
I think the ordering is clever with the way you've weaved in and out of XDG.  But it is also complex the way we weave from env variable to config back to env variable. 

This is kind of addressed in the upper section, but I'd lay out the intention of XDG in a more upfront manner. There are at least 4 distinctive layers of customization profiles here:

1. User env has no XDG_*, gets pure defaults (which fall back to XDG inspired defaults)
2. User env has XDG_*, but other wise pure defaults (data starts moving around)
3. User sets SPACK_HOME (Move everything together)
4. User starts playing with all the other knobs to get truly custom data movements (with a further hierarchy between config and env variables). 

This was a little confusing to me when reading. I'd reorder for the explanation. 

I'd go with a table showing the defaults and XDG mappings. Then I'd say something like:

"This is intended to map to the XDG standard which allows users to collectively customize where data goes by default across many programs. We have also provided a way to customize specifically for spack."

1. Everything is designed to nest under $SPACK_HOME for a wholistic data relocation strategy
2. $SPACK_HOME is set by
- (Env) SPACK_HOME
- (Config) config:locations:home
- (Default) XDG_CONFIG_HOME or ~/.local/spack
3. Specific sections can still be re-located independent of SPACK_HOME or XDG via env-variables or config

Then show the hierarchy for $data_home, or maybe present them all as a table?

2026-04-14 21:00 UTC, psakievich commented on lib/spack/spack/schema/config.py
> +                    "disable_env": {"type": "boolean"},
Hmm I had the same thought. What's the resolution on this one? It's a big PR so I definitely could have missed the docs on it.

2026-04-14 21:37 UTC, becker33 commented on lib/spack/spack/main.py
> +    for scope in cfg.scopes.values():
If you already have an override for the location or you already have SPACK_USER_CONFIG_PATH, then you won't hit this.

2026-04-15 06:15 UTC, haampie requested changes
This is probably one of the most breaking PRs in a long time 😬 and to me the benefits are marginal.

I think it's very risky to merge this, cause it undermines the narrative that Spack v1 is a stable tool. I would not merge this before it is made backward compatible.

Review from a user perspective without looking at the code and pr description (say I just updated Spack).

First thing I see is multiline warnings on each command:

```
==> Warning: Bypassing config in '/Users/user/.spack' in favor of '/Users/user/.config/spack'.
    Detected config in old location: '/Users/user/.config/spack'.
    Set `SPACK_USER_CONFIG_PATH` or modify your include.yaml to use '/Users/user/.spack'
    or move files from '/Users/user/.spack' to '/Users/user/.config/spack' to suppress this warning.
```

* What does "bypassing config" mean and why does the second line say "detected"? Raises the question if you detect it, why can't you use it?
* I have no means to judge whether (1) `SPACK_USER_CONFIG`, (2) `include.yaml` (I've never used this and wouldn't even know the syntax, also... what include.yaml?), or (3) "move files" (what files?) is better.

As a Spack developer I happen to know that `mv ~/.spack ~/.config/spack` is not what is meant. Other users won't have a clue. They certainly won't know that `~/.spack/bootstrap` is not relocatable.

Normally (buildcache, package repo, config deprecations) these warning messages show a command to run to migrate. Not here...

Next thing I tried was `spack find`, which worked 🤞. Then `spack config blame c<tab>` and it spits out the 4 line warning again (annoying). That's how I learned that the warning indeed means it does not respect my user config.

Running `spack install zlib` it installs `zlib` in `$spack/opt/spack` but clones a fresh `spack-packages` on a different commit. That's going to frustrate so many users.

I do not get why Spack is backwards compatible with `install_tree`, but that it refuses to use my config from `~/.spack`, even though I never had a `~/.local/spack` dir.

In my opinion you _should_ make this backwards compatible and just branch on existence of `~/.spack` and non-existence of `~/.local/spack`, if so assume old Spack structure. Then deprecate `~/.spack` in v1.3 or v1.4.

---

Few more thoughts:

* It's likely breaking existing CI workflows: fresh clone of spack to `$ci_temp_dir/spack`; the expectation was that installs go into `$ci_temp_dir/spack/opt/spack`, but now they end up in `~/.local/share/spack/installs`. If there's no isolation (jenkins, self-hosted gitlab runners) these are possibly persistent. That will probably raise a bunch of user complaints. How should user configure this?
* `~/.local/share/spack/installs` is shared, that complicates having two Spack instances say `v1.3` and `v1.4` where `v1.4` migrates the database to a new format as a side effect of saving; now the `v1.3` instance is no longer usable.
*  the path `~/.local/share/spack/installs` is longer than my previous `~/spack/opt/spack`; deeply nested paths are bad for performance (kernel has to resolve them, realpath is more stat calls) and can run into [path length and other limits](https://github.com/spack/spack/issues/33237) faster.
* On HPC systems, the home dir is not particularly fast; I would normally always `cd` to the faster shared filesystem, clone Spack there, and then run install. Now I would have to clone it, configure it, and then install. That's another step, I'm sure we'll get complaints about that, given that all our examples of using spack are `git clone; . setup-env.sh; spack install`. (In that sense I'm also confused that people asked for this...)

2026-04-15 07:57 UTC, alalazo commented
I also tried the PR briefly, and agree with @haampie that we should make it backward compatible first. Asking the users to update manually after a `git pull` if they want to keep using their configuration doesn't seem very user friendly.

At a high-level I think it would be better to have _a single marker_ that tells Spack which "layout" is in use, instead of migrating parts of the configuration per-path. The current per-path fallback heuristics are fragile because they have no single source of truth. A single marker solves this:
- Once a user is on XDG, all paths use XDG defaults consistently. 
- If on old layout, all paths use old layout defaults.

If possible, I'd try to stick to:
```
New spack instances should get XDG paths automatically, but existing users should only move when they ask to.
```
and avoid emitting warnings on each command.

### More detailed considerations on warnings and defaults

The warnings are _really_ shown every time:
<img width="1562" height="795" alt="Screenshot from 2026-04-15 09-04-38" src="https://github.com/user-attachments/assets/33216e5c-fd65-42e0-a19c-575aa580f34c" />

which will likely cause a lot of gripes (see above where I ask for `--help` on a command). As a minor point, the old location is wrong in the message (that's the new location).

On top of not accounting for the default config location, it seems to me that moving defaults (e.g. from `$spack` to `$data_home`) may also break people, if they relied on the previous default values:
1. `$spack/var/spack/cache -> $data_home/downloads` may cause unwanted downloads if people relied on the source cache. Wondering if we have use cases where `$spack` is persisted somewhere to avoid network usage, but `$data_home` is not which would cause downloads every new run / job in CI.
3. `$spack/share/spack/{modules,lmod} -> $data_home/{modules,lmod}` will break `spack module {tcl,lmod} refresh` etc. if users relied on the previous default directory for module files
4. Packages that requires license files will fail to find them in the old location.
5. Existing binary cache signing setups that rely on keys in `$spack/var/spack/gpg` will break

2026-04-15 08:26 UTC, haampie commented on lib/spack/spack/paths.py
> +    used for builds. Resolve all variables that are XDG-dependent, in
This feels suboptimal. For any new lazy constant added, you have to remember to extend it. Also, you don't call it in the new installer (and preferably shouldn't).

It'd be better to wrap these constants in an other object and pass them as function argument (i.e. serialization in the spawn/forkserver case):

1. In the spawn case you can't expect the subprocess to reinitialize the state exactly as the parent process.
2. Not all functions that use multiprocessing want to use `GlobalStateMarshaler`, because it has enormous overhead: it serializes the active environment (afaik redundantly, but well...).

2026-05-22 08:46 UTC, alalazo reviewed
It seems to me that a user with an old Spack instance alongside a new one can't silence the warning that gets printed on each command. This is a real issue, which a non-negligible amount of users will hit.

Sometimes ago, in DMs over Slack we talked about automatically migrating configurations, so that a Spack instance after this PR:
- Would initialize its configuration from old configuration, if old exists and new does not
- After that it will always read from the new locations

This would in principle prevent the issue with warnings, and will avoid runtime decisions on which layout to use based on poking the filesystem. Was this considered? In case what would be the issues trying to do things that way?

2026-05-22 08:46 UTC, alalazo commented on lib/spack/spack/main.py
> +    tty.warn(msg)
I started by test driving this PR on my current instance of Spack. I think we can improve the wording of this message:

<img width="1652" height="260" alt="Image" src="https://github.com/user-attachments/assets/1707e2ad-d06b-4ccc-a92c-093fba12627a" />

Issues I found:
- The slash in `config/user-cache-path` seems like a path, so may be confusing
- `User cache path fallback`: without reading the PR code, I don't know what that implies
- `If all Spack instances ...`: here we miss the _why_ we need all Spack instances >= 1.2 and what are the consequences of `spack micrate --clear`

I'm about to read the PR to find out 🙂

2026-05-22 08:46 UTC, alalazo commented on lib/spack/spack/main.py
> +    from spack.paths import locations as paths
Is there any reason for this import in the middle of a function? Can we remove it?

2026-05-22 08:46 UTC, alalazo commented on lib/spack/spack/main.py
> +    tty.warn(msg)
It seems we get this warning by default at the end of each command after a `git pull`, until further action is taken. That was one of my complaint at https://github.com/spack/spack/pull/47615#issuecomment-4250250269 

<img width="2306" height="209" alt="Image" src="https://github.com/user-attachments/assets/e967aad6-5bd0-46ff-a390-b2cf8201bb90" />

If I was using a production instance on the side at a version lower than v1.2, at this point I would be very unsure what to do...

2026-05-22 08:46 UTC, alalazo commented on lib/spack/spack/main.py
(Sharing thoughts on a different approach to path migration) I was thinking about auto-migration instead of the fallback mechanism we currently have in the PR, in particular for the use case of a user with two Spack clones at different prefixes, both with installs.

We can handle it as follows:
- Each clone runs its own auto-migration and writes its own site config (`$spack/etc/spack/config.yaml`) pinning its own `$spack/opt/spack`. The two site configs are therefore independent of each other.
- The shared user config in `~/.config/spack/` is the result of whichever clone ran auto-migration first.
- Path overrides are instance-specific and belong in the site scope.
- We can leave a sentinel file the first time we go through this process for a given scope, instead of repeatedly checking for existence of certain files on the filesystem. In this way it's trivial to know if the process was correctly executed before.

The result would be:

- Clone A reads user config from `~/.config/spack/`, resolves `install_tree:root` to `<prefix-A>/opt/spack` via its own site config.
- Clone B reads the same user config, resolves `install_tree:root` to `<prefix-B>/opt/spack` via its own site config.
- Old Spack instances (< 1.2) still read from `~/.spack/` and write to their own `$spack/opt/spack`. They are unaware of `~/.config/spack/` entirely.

Reasoning at a high-level, this approach wouldn't require any runtime detection mechanism, but it would ideally be something like:
```python
# In main.py, before create_incremental()
if not spack.migrate.auto_migration_done():
    spack.migrate.run_auto_migration()
```
and from there on we would deal with the new layout only.

2026-05-22 09:17 UTC, alalazo requested changes
Requesting changes to block merging until we agree on a migration path. 

At the moment migration seems difficult, in particular for users with another Spack instance at an earlier version - which to the best of my understanding have no way to cleanly migrate the new instance and silence the warning.

Messages are also confusing. This one for instance:

<img width="1721" height="290" alt="Image" src="https://github.com/user-attachments/assets/1e06583c-fcf5-4229-b5b0-b9b513195d1f" />

comes from the migration command itself - so a user see something migrated and gets a warning immediately after that. This leaves the impression the entire state of Spack is unreliable.

In the previous comment I suggested an alternative approach that may be viable to migrate configuration - if we want to discuss it.

2026-05-22 19:50 UTC, scheibelp commented
> I was thinking about auto-migration 

Auto-copying runs the risk of multiple spack instances silently updating divergent configs/package repos. e.g. if a user isn't aware of this, and uses the default package repo for creating PRs to the spack-packages repo, this could be frustrating.

IMO the best compromise would be to not print a warning if a new spack instance doesn't use `~/.spack`
- (but do print a warning if a new spack instance defaults to `~/.spack`)
- So if they have pre-1.2 instances, they run `spack migrate` (no `--clear`)
  - `spack migrate --i-need-old-spack` would warn them about divergent cache/configs
- The warning stops; old spack uses `~/.spack` for cache+configs; new spack uses `~/.local/state/spack` for cache and `~/.config/spack` for configs
- (the current warning logic already collects enough info to decide this, so this is easy to do)

This change would make it easy to disable the warning, while making the tradeoffs explicit.

I added `--i-need-old-spack` to `spack migrate` since the last review, which prints how one can currently avoid this warning message; at the moment it does not provide a way to let new spack use new locations and old spack to use old locations without a warning message.

2026-06-05 23:01 UTC, scheibelp commented
Closing in favor of https://github.com/spack/spack/pull/52468

2026-06-05 23:01 UTC, closed without merging