[WIP] detect pch output and set mode=cpp in that case
spack/spack pull request #8853
Opened 2018-08-01 02:26 UTC by scheibelp

See: https://github.com/spack/spack/issues/8640

Spack should operate in cpp mode (vs. ld/ccld mode) when creating .pch files (precompiled headers). This adds a rudimentary check based on the presence of `-o`. This doesn't detect all cases of creating precompiled headers but doing that 100%-accurately requires parsing the input file from the command which would take significantly more effort.

Note that I have tried building WxPython (mentioned in #8640, the current only test case for this) and it still fails but as far as I can tell right now it is not related to doing the wrong thing for precompiled headers (i.e. adding this patch gets past the original failure).

2020-08-21 17:01 UTC, adamjstewart commented
@scheibelp is this still a WIP or can it be closed?

2021-04-20 00:18 UTC, becker33 requested changes

2021-04-20 00:18 UTC, becker33 commented on lib/spack/env/cc
> +done
This should be encorporated into the following block, which also iterates over all of the arguments and sets the mode accordingly

2022-05-05 10:33 UTC, alalazo commented
Closing as stale. Feel free to reopen if you think it's still relevant.

2022-05-05 10:33 UTC, closed without merging